### ISSUE TITLE
No playback, just "Loading Media"

### ISSUE THREAD

**Issue by EternisRequiem** [SamDel/ChromeCast-Desktop-Audio-Streamer#10]
Recognizes my Chromecast, brings up "Desktop Stream", blue bar cycles, and nothing happens.  Eventually the UI says "Idle" again.

**Comment by SamDel** [comment]
I'm not sure what goes wrong there.
You use a Chromecast TV device (blue bar), in old versions of this app there was a problem for Chromecast TV with the audio format that was used. Do you have the latest version?
Can you enable logging in the config file, and post the log?

**Comment by barduar** [comment]
Hello, I came across the same problem, the simple fix that worked for me:  I went into windows advanced firewall settings and removed the block that windows had set up. Even though I pressed allow on private and public networks, when i first booted the program. 
![capture](https://user-images.githubusercontent.com/38397896/38777835-6be55c4a-40a6-11e8-9d9f-c41c3b1f7498.PNG)
Hope this helps!

**Comment by SamDel** [comment]
Another thing that can go wrong here is that the application doesn't automatically get the right IP address to use for streaming. The Chromecast device can't load the stream then.

There are some improvements in getting the rigth IP address in version [1.3](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/releases/tag/v1%2C3). You can also try changing the IP address that's used for streaming in the UI now.
