### ISSUE TITLE
Multi-channel audio possible?

### ISSUE THREAD

**Issue by andersborgabiro** [SamDel/ChromeCast-Desktop-Audio-Streamer#103]
I played a 5.1 FLAC 24-bit (ripped from Blu-ray, and 5.1 when played locally) and it was converted to stereo before being transferred to the Chromecast (at least the amplifier considers it a stereo stream).

Is it technically possible to achieve at least 5.1?

**Comment by SamDel** [comment]
Not sure, but it might be possible. 

This tool always converts to stereo / two channels now (version 3.5, [here in code](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/blob/ee2b1f44b023db51e5244bbee61b6b805c0e30c4/Source/ChromeCast.Desktop.AudioStreamer/Streaming/LoopbackRecorder.cs#L191)).
In [Setup 3.5.6.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/6454879/Setup.3.5.6.zip) the audio isn't converted to stereo, so I think/hope all captured channels are send to the device. 

I can't test it myself so I'm not sure what happens. Can you try (with wav as stream format on the options tab) and let it know?

**Comment by andersborgabiro** [comment]
This is my quick test result:
5.1 in, WAV out: Multi In
Stereo, in WAV out: Multi In (!)
Anything in, MP3 out: Stereo

**Comment by SamDel** [comment]
Thanks!

> 5.1 in, WAV out: Multi In
> Stereo, in WAV out: Multi In (!)

I think it works like so: when you play a stereo track the two channels are converted to the number of tracks your soundcard has (a different sound in each speaker?). This tool captures the sound from the soundcard, so it always has the same number of channels your soundcard has.

> Anything in, MP3 out: Stereo

as expected.

Do you think there should be an option to always convert to stereo?

**Comment by andersborgabiro** [comment]
Only if it would otherwise fail I guess.

That said, multichannel simulations from (actually) stereo audio will not be possible to activate on my amp if it receives multichannel audio. I don't know if that's the norm.

When back home I can check this better.

**Comment by andersborgabiro** [comment]
Do you know how audio in Atmos format would be handled? Converted to the nearest equivalent the audio card supports before you get an audio stream? Does the Chromecast support Atmos?

**Comment by SamDel** [comment]
In [Setup 3.5.8.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/6459287/Setup.3.5.8.zip) I added an option for it. I think in all/most scenarios the conversion is taken care of by the drivers. I was also thinking about the bandwidth. For me, streaming to one device in stereo takes ~2.4Mbps, how's the bandwidth for you with multiple channels?

In my understanding with Atmos a lot more channels can be added. It looks like Chromecast supports it, so it could work with version 3.5.8. Maybe someone can do a test!

**Comment by andersborgabiro** [comment]
VLC paused: still 7 Mbps
VLC exited: no data transfer

So this might actually be a quirk in VLC (keeping audio active even when not playing).

**Comment by SamDel** [comment]
True. You have to restart the stream if you want to change the audio quality, causing delays.

**Comment by andersborgabiro** [comment]
Thanks for updating the application.

**Comment by SamDel** [comment]
Thank you for testing! Very nice that this application has multi-channel support now 😃 !
I will create an 'official' release (3.6) in a week or so.

If anyone can do an Atmos test, please leave a comment!

**Comment by SamDel** [comment]
[Version 3.6](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/releases/tag/v3.6)
