### ISSUE TITLE
Desktop Audio Streamer won't start

### ISSUE THREAD

**Issue by AJNiteOwl** [SamDel/ChromeCast-Desktop-Audio-Streamer#107]
Since the latest update of Win 10 23/3/2021 I haven't been able to get DAS to start. I have tried repairing (used setup to activate and comes up with Repair bulleted. Tried repair a couple of times - no better.  Then uninstalled and re-installed still won't work?

Also noticed some of the speaker options (bluetooth and DAS) no longer available in task bar at bottom of Win 10 screen.  Will chase this up in parallel.

I hear MS are looking to move drivers to a separate directory other than Program Files (x86) in a future update as that folder has become over populated.

**Comment by SamDel** [comment]
If DAS doesn't start there's most likely an error in the 'Event Viewer - Windows Logs - Application' log. What does it say?

**Comment by AJNiteOwl** [comment]
Hi Sam

 

I couldn’t find any entry in Event Viewer when starting it up (looks like it doesn’t even try to start).

 

MS support are stepping through issues in Device Manager – looks like most of the Bluetooth drivers (including Bose headphones and other speakers) are not completely installed at the Win 10 update on 23/3/21.

 

This appears to be a known problem and it looks like there are a number of drivers that have completed the install correctly.  Going into Device Manager and asking to update drivers (one by one) doesn’t help but will try uninstalling and reinstalling them next.

 

I have disabled “compattelrunner.exe” as I understand it runs in the background at restart (including out of Hibernation) and adds a lot of time to restart process checking for updates and changing background screen etc etc.  Maybe that will hunt down missing driver parts?

 

Regards

Andrew

 

Email   ***@***.***> ***@***.***

 

-----------------------------------------------------------------------------------------------------------------------
This email message and any attachments are confidential and are subject to legal privilege. If you have received this email in error, please advise the sender immediately and destroy the message and any attachments. If you are not the intended recipient you are notified that any use, distribution, amendment, copying or any action taken or admitted to be taken in reliance of this message or attachments is prohibited.

**Comment by SamDel** [comment]
It's hard to tell why DAS doesn't start, maybe because of the audio drivers. It sounds like you have to fix the Windows installation first.

**Comment by AJNiteOwl** [comment]
Ok Sam, all fixed - I see you have sorted in release 3.6 (and 3.7) - saw your comment about Windows removing Windows default and possibly moving to .Net 4.7.2?
