### ISSUE TITLE
HDMI audio output, doesn't stream

### ISSUE THREAD

**Issue by eminos** [SamDel/ChromeCast-Desktop-Audio-Streamer#11]
I just tried this on both my Laptop and my HTPC (Windows 10, connected with HDMI to TV).
On the Laptop it works fine, I can stream audio playback to my Home Minis.
But on the HTPC it never starts streaming the audio, just says "Idle".

I suspect that's because I'm using the HDMI for audio output from the Windows HTPC.
Is there a fix for this?

**Comment by eminos** [comment]
Yea, I can confirm the HDMI audio output is the issue here.
If I switch the default output in Sound -> Playback settings to "Digital Audio (S/PDIF)" it starts to stream the sound just fine. As soon as I switch back to "LG TV, Intel Display Audio" it stops.

**Comment by SamDel** [comment]
Thanks, good research.

I probably never tried but I have the same behaviour when plugging in a HDMI computer monitor.
and after I found this message on [audacity](http://manual.audacityteam.org/man/tutorial_recording_computer_playback_on_windows.html):

> You must play the audio you want to record using the same sound device that has the "Stereo Mix" or similar input. You cannot play audio through an HDMI output or through a headset, headphones or speakers that connect via USB or wirelessly then record that playback using the stereo mix input of the built-in sound device.

I found out that I also have the bahaviour when plugging in a headphone. Have you tried a headphone?

**Comment by eminos** [comment]
I was about to try with headphones but now my Home Minis are not showing up anymore, only the Chromecast. I'm not sure why.

But is this, HDMI audio output, fixable? To have your software stream the HDMI audio? Maybe it could be configurable (choose output device)?

**Comment by SamDel** [comment]
You can add your devices in the config if they don't show up.

Can you try [0.9](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/releases)? 
I added a dropdown for the recording device, with the default device selected by default.

**Comment by eminos** [comment]
All devices showed up before, but now they don't. On the HTPC all devices still show up.

Anyway, just tried 0.9. And it works! Awesome :)

**Comment by SamDel** [comment]
Sometimes a reboot helps ;-). That's fast, glad it works!

**Comment by eminos** [comment]
Ok. I'll try a reboot.
Maybe you could also add a "scan for chromecast / home devices" feature :)

**Comment by SamDel** [comment]
It's scanning for devices at startup now. It stops after a minute or so. 
Maybe I can add a button to start scanning again after you've changed something. Is that what you mean?

**Comment by SamDel** [comment]
I added a button to scan again for devices in version [1.3](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/releases/tag/v1%2C3).
I'm going to close this issue.
