### ISSUE TITLE
Chosen IP4 address not remembered

### ISSUE THREAD

**Issue by jorbig** [SamDel/ChromeCast-Desktop-Audio-Streamer#112]
Your app works great! But by default, it selects my ZeroTier IP address, which doesn't work. I then have to set to my local IP (192.168.X.X) manually. I hoped your app would remember this setting, but everytime I restart it, it defaults back to the ZeroTier IP again... Easily fixed?

**Comment by SamDel** [comment]
Thanks! The IP wasn't saved to the config file. How's [Setup 3.7.3.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/6834745/Setup.3.7.3.zip) for you?

**Comment by jorbig** [comment]
Great! Works fine now. Many thanks for this quick fix.

Op za 17 jul. 2021 om 15:14 schreef SamDel ***@***.***>:

**Comment by SamDel** [comment]
Nice, thanks!

**Comment by SamDel** [comment]
The fix is in release version [3.8](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/releases/tag/v3.8).
