### ISSUE TITLE
IP Assignments in config file

### ISSUE THREAD

**Issue by FA-Bubba** [SamDel/ChromeCast-Desktop-Audio-Streamer#114]
You had previously suggested:
You can also edit the config file in the install folder, and change the value of IpAddressesDevices to
<add key="IpAddressesDevices" value="192.168.1.239,Family Room TV;192.168.1.125,PlayRoom Speaker;192.168.1.156,Basement Speaker;192.168.1.187,Office Speaker;192.168.1.178,Guest Room Speaker;192.168.1.107,Family Room Speaker" />

I recently added a device with a Static IP Address, and I wanted to update the "<add key" entry you had previously suggested...

I shut down DAS, and opened user.config, but my previous entry (shown above) was not there.  Please let me know where this "<add key..." line is supposed to go**, and if it is automatically added when installing a new version of DAS.

Thank you!

** I was looking here:
C:\Users\<UserName>\AppData\Local\ChromeCast\ChromeCast.Desktop.AudioS_Url_r2n4cjyianvvlnkczlfzrmj0rymldepp\3.7.2.0\user.config

**Comment by SamDel** [comment]
That key is in the config file in the install folder:
```
C:\Program Files (x86)\Desktop Audio Streamer\Desktop Audio Streamer\ChromeCast.Desktop.AudioStreamer.exe.config
```

**Comment by FA-Bubba** [comment]
THANK YOU !!!
