### ISSUE TITLE
HiDPI design/position issues?

### ISSUE THREAD

**Issue by eminos** [SamDel/ChromeCast-Desktop-Audio-Streamer#12]
There seems to be some issues with the play button position. I'm not sure why, but it might be Windows scaling (HiDPI) related?

![2018-04-12 23_12_25-new issue samdel_chromecast-desktop-audio-streamer](https://user-images.githubusercontent.com/1682784/38704571-169d9622-3ea7-11e8-9ef1-4f8115d212c7.png)

**Comment by SamDel** [comment]
Thanks, fixed it. Will be in the next release.
