### ISSUE TITLE
Need method to prevent device discovery

### ISSUE THREAD

**Issue by Cheeselets** [SamDel/ChromeCast-Desktop-Audio-Streamer#131]
I own a Sony Smart TV that is accessible via Chromecast.
DAS discovers it automatically BUT while using DAS to another device it seems to sometimes poll the TV which switches the mode it is in or switches on the TV when it is in standby.

Is there a method to make DAS *not* discover a device.

Something like 

'del key="IpAddressesDevices" value="192.168.1.100,SonyTV"' 

in the config file, to make up an analogue of the method to add devices. ???

Many thanks for your assistance & the very useful audio streamer.

:)

**Comment by SamDel** [comment]
A method like that didn't exist. I added the config option in [Setup 4.0.1.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/8736790/Setup.4.0.1.zip).

Usage:
`<add key="IgnoreIpAddressesDevices" value="192.168.0.1;192.168.0.2" />`

DAS polls all devices in the list every 15 seconds for the latest state, maybe that triggers something on the Sony TV. You can also check the log to see the messages that are send to the device.

**Comment by Cheeselets** [comment]
Thank you so much for the blindingly quick response !!!

Works Perfectly 💯 🥇 

And once again thank you for the Desktop Audio Streamer [DAS], it enables me to use a Google Nest Mini as my Speaker on a Win 7 PC. 
(Yes, I know Win 7 is deprecated ..... don't get me started on Win 10/11 <Windows 'Meh' or 'Fisher-Price Edition'> )

:)

**Comment by SamDel** [comment]
Nice, thanks 🙂 !
