### ISSUE TITLE
audio device in Windows via the ChromeCast desktop audio streamer

### ISSUE THREAD

**Issue by tsk7mde** [SamDel/ChromeCast-Desktop-Audio-Streamer#144]
Hello,

currently I use "VB-CABLE Virtual Audio Device" to send the music from the hi res media player to "ChromeCast-Desktop-Audio-Streamer". Can't you simulate an audio device in Windows via the software (ChromeCast desktop audio streamer with 192khz,24bit audio) so that any software on the PC can directly send the music to the "ChromeCast desktop audio streamer" e.g. MediaMonkey 5, qobuz player etc .
FYI: it should be ensured that a different device is used so that the default audio from windows does not interfere with the music.
Or if you use several players and want to distribute different streams, you also need different audio devices in Windows

Thanks

**Comment by SamDel** [comment]
Then you have to embed a virtual audio device into ChromeCast desktop audio streamer I think!?
I don't have experience writing audio drivers and I'm not sure if it's possible for an app like this to also identify as an audio device!?

**Comment by tsk7mde** [comment]
Okay I see.
Alternatively, you could also allow several "Recording devices" with the "ChromeCast desktop audio streamer" application, which you can then distribute to the streaming devices. Then no driver needs to be written and I continue to use "VB-CABLE Virtual Audio Device" for the connection. It just has to be possible to manage more "recording devices" and an option to output them to different "Chromecast Devices". Thanks and regards

**Comment by SamDel** [comment]
An option to select a recording device for every Chromcast device connection you mean? That should be possible.

**Comment by tsk7mde** [comment]
yes, eg. 

<img width="1172" alt="2023-06-09 01_38_27-We Make It (Instrumental) - King Mzaiza Music" src="https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/assets/7759288/fd10d078-48a0-4694-a5d7-dabee951dda3">

<img width="1063" alt="2023-06-09 01_41_12-Desktop Audio Streamer" src="https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/assets/7759288/e11919cd-e80f-4d91-a046-2d90b8a44e80">

**Comment by tsk7mde** [comment]
Of course it would be great if you can save the settings and have presets (audio input and stream output)

**Comment by SamDel** [comment]
It's a lot of work rewriting the application like this. I think it's possible when you run two instances of the application.
In [Setup 5.1.5.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/11703031/Setup.5.1.5.zip) it's possible to run two instances. When you make a copy of the install folder the settings are saved per instance.

Not ideal, but can you try?

**Comment by tsk7mde** [comment]
<img width="302" alt="2023-06-09 11_38_35-Desktop Audio Streamer" src="https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/assets/7759288/878f502c-a677-45a1-95e3-d9339b9239f4">
<img width="1093" alt="2023-06-09 11_37_36-Desktop Audio Streamer" src="https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/assets/7759288/2e476091-a910-4a21-9983-c66ebdd9e950">
<img width="161" alt="2023-06-09 11_42_41-" src="https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/assets/7759288/24a6ff75-63b5-42c8-9a4e-fa0bd47adf63">

**Comment by SamDel** [comment]
> But the minimize option after startup doesn't work on the second instance.

It works for me, I even tried with 5 instances. What goes wrong, is the application closed?

**Comment by SamDel** [comment]
In [Setup 5.1.6.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/11778174/Setup.5.1.6.zip) I added the name of the recording device to the UI. It's in the titlebar and in the mouseover of the tray-icon, and only shown when you selected a recording device other than the default.

I also moved the project to the .Net 7 framework, it can be that's added on installation.

**Comment by tsk7mde** [comment]
Thank you! That they provide the application! greeting

**Comment by SamDel** [comment]
You're welcome. I will create a new release shortly!

**Comment by SamDel** [comment]
New release: [Version 5.2](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/releases/tag/v5.2) (identical to 5.1.6)
