### ISSUE TITLE
Connects to speaker but no sound is heard

### ISSUE THREAD

**Issue by eldontyrellcorp2019** [SamDel/ChromeCast-Desktop-Audio-Streamer#149]
Version 5.1.6 worked the first time I used it (see https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/issues/147)

But now, no music is heard after I connect to a speaker. The status in the app says "Idle" but I know it is connected because I can control the speaker volume with app slider.

Possibly related is a Windows .NET 7 error message that I get every time I launch the app or scan again for devices (which I ignore and close, and the app stays open).

I have a firewall rule for both inbound and outbound connections, and I have created a port forwarding rule for port 8009 in my Synology WRX560 router, using my PC's IP address. Havel also added the exe file to the split tunnelling settings in my NordVPN app to bypass the PC's VPN connection.

Windows 10 log, app log, and some screenshots are attached. Thanks for your help.

[APP ERROR LOG - Destop Audio Streamer.txt](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/12331151/APP.ERROR.LOG.-.Destop.Audio.Streamer.txt)
[WINDOWS ERROR MESSAGE - Destop Audio Streamer.txt](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/12331152/WINDOWS.ERROR.MESSAGE.-.Destop.Audio.Streamer.txt)
![Screenshot CDAStreamer error](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/assets/141975559/ac857ed9-de51-4918-bfd2-c5c50c2343a7)
![Screenshot CDAStreamer control panel](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/assets/141975559/a60a29a9-5757-4369-ae33-d67d254968fd)

**Comment by SamDel** [comment]
Something goes wrong with the IP4 address that's used for the streaming connection. Are there entries in that dropdown on the option tab?


_The application can also be improved in a scenario like this._

**Comment by eldontyrellcorp2019** [comment]
Hi Sam, yes, there is my PC's IP - which is chosen - plus one other: 127.0.0.1

**Comment by FA-Bubba** [comment]
For what it is worth, I have assigned fixed IP addresses to each of my speakers, so they don't wander around the LAN...
FYI, I have 16 speakers, and some in groups.  The connections have been pretty good for a long time.

**Comment by SamDel** [comment]
Thanks. Does [Setup 5.3.1.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/12339190/Setup.5.3.1.zip) work for you?

**Comment by eldontyrellcorp2019** [comment]
> For what it is worth, I have assigned fixed IP addresses to each of my speakers, so they don't wander around the LAN... FYI, I have 16 speakers, and some in groups. The connections have been pretty good for a long time.

Yes, I do have static IPs for all my devices.

**Comment by eldontyrellcorp2019** [comment]
> Something goes wrong with the IP4 address that's used for the streaming connection. Are there entries in that dropdown on the option tab?
> 

Okay I've discovered the cause. Damn it, it's the VPN!

If I completely close the NordVPN app, Desktop Audio Streamer works as normal.

So I need to work out the cause. Perhaps some additional process/app/s needs to be added to the split tunnelling list - not just ChromeCast.Desktop.AudioStreamer.exe?

**Comment by SamDel** [comment]
In code it fails on [this line](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/blob/bb6dcd760e2aeb43bce0e7104e34c1a180f5165d/Source/ChromeCast.Desktop.AudioStreamer/Streaming/StreamingRequestsListener.cs#L53). The [LocalEndPoint property of the Socket class](https://learn.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.localendpoint?view=net-7.0&devlangs=csharp&f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(System.Net.Sockets.Socket.LocalEndPoint)%3Bk(DevLang-csharp)%26rd%3Dtrue) returns null in your case. Because of that the streaming connection is not opened (No 'Streaming from ...' line in your log) and loading the stream by the device fails.

I tried to fix that in 5.3.1. With the information you provided I can maybe do a test (with VPN) later.

**Comment by eldontyrellcorp2019** [comment]
> In code it fails on [this line](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/blob/bb6dcd760e2aeb43bce0e7104e34c1a180f5165d/Source/ChromeCast.Desktop.AudioStreamer/Streaming/StreamingRequestsListener.cs#L53). The [LocalEndPoint property of the Socket class](https://learn.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.localendpoint?view=net-7.0&devlangs=csharp&f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(System.Net.Sockets.Socket.LocalEndPoint)%3Bk(DevLang-csharp)%26rd%3Dtrue) returns null in your case. Because of that the streaming connection is not opened (No 'Streaming from ...' line in your log) and loading the stream by the device fails.
> 
> I tried to fix that in 5.3.1. With the information you provided I can maybe do a test (with VPN) later.

Thanks for that. I'll just manage in the meantime :)
