### ISSUE TITLE
Bad sound quality

### ISSUE THREAD

**Issue by timsookram** [SamDel/ChromeCast-Desktop-Audio-Streamer#15]
The audio sounds like a low-bitrate mp3 over my chromecast audio.
This is a good application but the sound quality is a dealbreaker.
Using Windows 10.

**Comment by SamDel** [comment]
Sorry for the late reponse.

In [2.0](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/releases/tag/v2.0) you can change the stream format, does that make the quality better? Or you can try changing the recording source.
