### ISSUE TITLE
restarting over and over again

### ISSUE THREAD

**Issue by bbakker-byte** [SamDel/ChromeCast-Desktop-Audio-Streamer#152]
Hello SamDel

since a little while the DAS app on de chromecast keeps restarting. 
I get no audio. I don't know when this is started exactly. because i'm not using it every day,
We use this device for watching tv also and that is working fine.
I've installed the latest version, but this didn't help. 

UPDATE : *** IT'S RESOLVED !!!: I had a second fixed IP on my network controller. 

Thanks in advance.

I've added my log:

<details><summary>Log</summary>
<p>

Set stream format to Wav_24bit

Set stream format to Mp3_320

Check For Silence: Send Silence (0,0266151)

out [4:08:29 PM][192.168.1.107:8009] [Idle]: {"requestId":8,"type":"GET_STATUS"}

in [4:08:29 PM] [192.168.1.107:8009] [Idle]: {"requestId":8,"status":{"applications":[{"appId":"CC1AD845","appType":"WEB","displayName":"Default Media Receiver","iconUrl":"","isIdleScreen":false,"launchedFromCloud":false,"namespaces":[{"name":"urn:x-cast:com.google.cast.cac"},{"name":"urn:x-cast:com.google.cast.debugoverlay"},{"name":"urn:x-cast:com.google.cast.media"}],"sessionId":"6817002a-73bd-433a-9101-4fbae7a241dc","statusText":"Default Media Receiver","transportId":"6817002a-73bd-433a-9101-4fbae7a241dc","universalAppId":"CC1AD845"}],"userEq":{},"volume":{"controlType":"attenuation","level":0.699999988079071,"muted":false,"stepInterval":0.05000000074505806}},"type":"RECEIVER_STATUS"}

Stream format set to Pcm 48000 16 bit

[4:08:34 PM] [192.168.1.107:8009] ResumePlaying

out [4:08:38 PM][192.168.1.107:8009] [LaunchingApplication]: {"type":"CONNECT"}

out [4:08:38 PM][192.168.1.107:8009] [LaunchingApplication]: {"appId":"CC1AD845","requestId":9,"type":"LAUNCH"}

in [4:08:38 PM] [192.168.1.107:8009] [LaunchingApplication]: {"requestId":9,"status":{"applications":[{"appId":"CC1AD845","appType":"WEB","displayName":"Default Media Receiver","iconUrl":"","isIdleScreen":false,"launchedFromCloud":false,"namespaces":[{"name":"urn:x-cast:com.google.cast.cac"},{"name":"urn:x-cast:com.google.cast.debugoverlay"},{"name":"urn:x-cast:com.google.cast.media"}],"sessionId":"6817002a-73bd-433a-9101-4fbae7a241dc","statusText":"Default Media Receiver","transportId":"6817002a-73bd-433a-9101-4fbae7a241dc","universalAppId":"CC1AD845"}],"userEq":{},"volume":{"controlType":"attenuation","level":0.699999988079071,"muted":false,"stepInterval":0.05000000074505806}},"type":"RECEIVER_STATUS"}

out [4:08:38 PM][192.168.1.107:8009] [LaunchedApplication]: {"type":"CONNECT"}

Stream format set to Pcm 48000 16 bit

Recording Stopped

out [4:08:38 PM][192.168.1.107:8009] [LoadingMedia]: {"autoplay":true,"currentTime":0,"activeTrackIds":[],"repeatMode":"REPEAT_OFF","media":{"contentId":"http://10.100.110.5:33053/","contentType":"audio/wav","streamType":"BUFFERED","metadata":{"type":0,"metadataType":0,"title":"Desktop Audio Streamer","images":[]}},"requestId":10,"type":"LOAD"}

in [4:08:38 PM] [192.168.1.107:8009] [LoadingMedia]: {"type":"MEDIA_STATUS","status":[{"mediaSessionId":3,"playbackRate":1,"playerState":"IDLE","currentTime":0,"supportedMediaCommands":12303,"volume":{"level":1,"muted":false},"activeTrackIds":[],"media":{"contentId":"http://10.100.110.5:33053/","contentType":"audio/wav","streamType":"BUFFERED","metadata":{"type":0,"metadataType":0,"title":"Desktop Audio Streamer","images":[]},"mediaCategory":"AUDIO"},"currentItemId":1,"extendedStatus":{"playerState":"LOADING","media":{"contentId":"http://10.100.110.5:33053/","contentType":"audio/wav","streamType":"BUFFERED","metadata":{"type":0,"metadataType":0,"title":"Desktop Audio Streamer","images":[]},"mediaCategory":"AUDIO"},"mediaSessionId":3},"repeatMode":"REPEAT_OFF"}],"requestId":0}

in [4:08:39 PM] [192.168.1.107:8009] [Idle]: {"requestId":10,"type":"LOAD_FAILED","detailedErrorCode":104,"itemId":1}

in [4:08:39 PM] [192.168.1.107:8009] [LoadFailed]: {"type":"MEDIA_STATUS","status":[{"mediaSessionId":3,"playbackRate":1,"playerState":"IDLE","currentTime":0,"supportedMediaCommands":12303,"volume":{"level":1,"muted":false},"currentItemId":1,"idleReason":"ERROR"}],"requestId":0}

in [4:08:39 PM] [192.168.1.107:8009] [Idle]: {"requestId":0,"status":{"applications":[{"appId":"CC1AD845","appType":"WEB","displayName":"Default Media Receiver","iconUrl":"","isIdleScreen":false,"launchedFromCloud":false,"namespaces":[{"name":"urn:x-cast:com.google.cast.cac"},{"name":"urn:x-cast:com.google.cast.debugoverlay"},{"name":"urn:x-cast:com.google.cast.media"}],"sessionId":"6817002a-73bd-433a-9101-4fbae7a241dc","statusText":"Default Media Receiver","transportId":"6817002a-73bd-433a-9101-4fbae7a241dc","universalAppId":"CC1AD845"}],"userEq":{},"volume":{"controlType":"attenuation","level":0.699999988079071,"muted":false,"stepInterval":0.05000000074505806}},"type":"RECEIVER_STATUS"}

Check For Silence: 2,4418004

Check For Silence: 3,4324127

Check For Silence: 4,4402013

Check For Silence: Send Silence (0,0001422)

out [4:08:44 PM][192.168.1.107:8009] [Idle]: {"requestId":11,"type":"GET_STATUS"}

in [4:08:44 PM] [192.168.1.107:8009] [Idle]: {"requestId":11,"status":{"applications":[{"appId":"CC1AD845","appType":"WEB","displayName":"Default Media Receiver","iconUrl":"","isIdleScreen":false,"launchedFromCloud":false,"namespaces":[{"name":"urn:x-cast:com.google.cast.cac"},{"name":"urn:x-cast:com.google.cast.debugoverlay"},{"name":"urn:x-cast:com.google.cast.media"}],"sessionId":"6817002a-73bd-433a-9101-4fbae7a241dc","statusText":"Default Media Receiver","transportId":"6817002a-73bd-433a-9101-4fbae7a241dc","universalAppId":"CC1AD845"}],"userEq":{},"volume":{"controlType":"attenuation","level":0.699999988079071,"muted":false,"stepInterval":0.05000000074505806}},"type":"RECEIVER_STATUS"}

Stream format set to Pcm 48000 16 bit

[4:08:49 PM] [192.168.1.107:8009] ResumePlaying

out [4:08:53 PM][192.168.1.107:8009] [LaunchingApplication]: {"type":"CONNECT"}

out [4:08:53 PM][192.168.1.107:8009] [LaunchingApplication]: {"appId":"CC1AD845","requestId":12,"type":"LAUNCH"}

in [4:08:53 PM] [192.168.1.107:8009] [LaunchingApplication]: {"requestId":12,"status":{"applications":[{"appId":"CC1AD845","appType":"WEB","displayName":"Default Media Receiver","iconUrl":"","isIdleScreen":false,"launchedFromCloud":false,"namespaces":[{"name":"urn:x-cast:com.google.cast.cac"},{"name":"urn:x-cast:com.google.cast.debugoverlay"},{"name":"urn:x-cast:com.google.cast.media"}],"sessionId":"6817002a-73bd-433a-9101-4fbae7a241dc","statusText":"Default Media Receiver","transportId":"6817002a-73bd-433a-9101-4fbae7a241dc","universalAppId":"CC1AD845"}],"userEq":{},"volume":{"controlType":"attenuation","level":0.699999988079071,"muted":false,"stepInterval":0.05000000074505806}},"type":"RECEIVER_STATUS"}

out [4:08:53 PM][192.168.1.107:8009] [LaunchedApplication]: {"type":"CONNECT"}

Stream format set to Pcm 48000 16 bit

Recording Stopped

out [4:08:53 PM][192.168.1.107:8009] [LoadingMedia]: {"autoplay":true,"currentTime":0,"activeTrackIds":[],"repeatMode":"REPEAT_OFF","media":{"contentId":"http://10.100.110.5:33053/","contentType":"audio/wav","streamType":"BUFFERED","metadata":{"type":0,"metadataType":0,"title":"Desktop Audio Streamer","images":[]}},"requestId":13,"type":"LOAD"}

in [4:08:54 PM] [192.168.1.107:8009] [LoadingMedia]: {"type":"MEDIA_STATUS","status":[{"mediaSessionId":4,"playbackRate":1,"playerState":"IDLE","currentTime":0,"supportedMediaCommands":12303,"volume":{"level":1,"muted":false},"activeTrackIds":[],"media":{"contentId":"http://10.100.110.5:33053/","contentType":"audio/wav","streamType":"BUFFERED","metadata":{"type":0,"metadataType":0,"title":"Desktop Audio Streamer","images":[]},"mediaCategory":"AUDIO"},"currentItemId":1,"extendedStatus":{"playerState":"LOADING","media":{"contentId":"http://10.100.110.5:33053/","contentType":"audio/wav","streamType":"BUFFERED","metadata":{"type":0,"metadataType":0,"title":"Desktop Audio Streamer","images":[]},"mediaCategory":"AUDIO"},"mediaSessionId":4},"repeatMode":"REPEAT_OFF"}],"requestId":0}

in [4:08:54 PM] [192.168.1.107:8009] [Idle]: {"requestId":13,"type":"LOAD_FAILED","detailedErrorCode":104,"itemId":1}

in [4:08:54 PM] [192.168.1.107:8009] [LoadFailed]: {"type":"MEDIA_STATUS","status":[{"mediaSessionId":4,"playbackRate":1,"playerState":"IDLE","currentTime":0,"supportedMediaCommands":12303,"volume":{"level":1,"muted":false},"currentItemId":1,"idleReason":"ERROR"}],"requestId":0}

in [4:08:54 PM] [192.168.1.107:8009] [Idle]: {"requestId":0,"status":{"applications":[{"appId":"CC1AD845","appType":"WEB","displayName":"Default Media Receiver","iconUrl":"","isIdleScreen":false,"launchedFromCloud":false,"namespaces":[{"name":"urn:x-cast:com.google.cast.cac"},{"name":"urn:x-cast:com.google.cast.debugoverlay"},{"name":"urn:x-cast:com.google.cast.media"}],"sessionId":"6817002a-73bd-433a-9101-4fbae7a241dc","statusText":"Default Media Receiver","transportId":"6817002a-73bd-433a-9101-4fbae7a241dc","universalAppId":"CC1AD845"}],"userEq":{},"volume":{"controlType":"attenuation","level":0.699999988079071,"muted":false,"stepInterval":0.05000000074505806}},"type":"RECEIVER_STATUS"}

Check For Silence: 2,357928

Check For Silence: 3,3511829

Check For Silence: 4,3589054

Check For Silence: Send Silence (0,0180753)

out [4:08:59 PM][192.168.1.107:8009] [Idle]: {"requestId":14,"type":"GET_STATUS"}

in [4:08:59 PM] [192.168.1.107:8009] [Idle]: {"requestId":14,"status":{"applications":[{"appId":"CC1AD845","appType":"WEB","displayName":"Default Media Receiver","iconUrl":"","isIdleScreen":false,"launchedFromCloud":false,"namespaces":[{"name":"urn:x-cast:com.google.cast.cac"},{"name":"urn:x-cast:com.google.cast.debugoverlay"},{"name":"urn:x-cast:com.google.cast.media"}],"sessionId":"6817002a-73bd-433a-9101-4fbae7a241dc","statusText":"Default Media Receiver","transportId":"6817002a-73bd-433a-9101-4fbae7a241dc","universalAppId":"CC1AD845"}],"userEq":{},"volume":{"controlType":"attenuation","level":0.699999988079071,"muted":false,"stepInterval":0.05000000074505806}},"type":"RECEIVER_STATUS"}

Stream format set to Pcm 48000 16 bit

[4:09:04 PM] [192.168.1.107:8009] ResumePlaying

out [4:09:08 PM][192.168.1.107:8009] [LaunchingApplication]: {"type":"CONNECT"}

out [4:09:08 PM][192.168.1.107:8009] [LaunchingApplication]: {"appId":"CC1AD845","requestId":15,"type":"LAUNCH"}

in [4:09:08 PM] [192.168.1.107:8009] [LaunchingApplication]: {"requestId":15,"status":{"applications":[{"appId":"CC1AD845","appType":"WEB","displayName":"Default Media Receiver","iconUrl":"","isIdleScreen":false,"launchedFromCloud":false,"namespaces":[{"name":"urn:x-cast:com.google.cast.cac"},{"name":"urn:x-cast:com.google.cast.debugoverlay"},{"name":"urn:x-cast:com.google.cast.media"}],"sessionId":"6817002a-73bd-433a-9101-4fbae7a241dc","statusText":"Default Media Receiver","transportId":"6817002a-73bd-433a-9101-4fbae7a241dc","universalAppId":"CC1AD845"}],"userEq":{},"volume":{"controlType":"attenuation","level":0.699999988079071,"muted":false,"stepInterval":0.05000000074505806}},"type":"RECEIVER_STATUS"}

out [4:09:08 PM][192.168.1.107:8009] [LaunchedApplication]: {"type":"CONNECT"}

Stream format set to Pcm 48000 16 bit

Recording Stopped

out [4:09:08 PM][192.168.1.107:8009] [LoadingMedia]: {"autoplay":true,"currentTime":0,"activeTrackIds":[],"repeatMode":"REPEAT_OFF","media":{"contentId":"http://10.100.110.5:33053/","contentType":"audio/wav","streamType":"BUFFERED","metadata":{"type":0,"metadataType":0,"title":"Desktop Audio Streamer","images":[]}},"requestId":16,"type":"LOAD"}

in [4:09:08 PM] [192.168.1.107:8009] [LoadingMedia]: {"type":"MEDIA_STATUS","status":[{"mediaSessionId":5,"playbackRate":1,"playerState":"IDLE","currentTime":0,"supportedMediaCommands":12303,"volume":{"level":1,"muted":false},"activeTrackIds":[],"media":{"contentId":"http://10.100.110.5:33053/","contentType":"audio/wav","streamType":"BUFFERED","metadata":{"type":0,"metadataType":0,"title":"Desktop Audio Streamer","images":[]},"mediaCategory":"AUDIO"},"currentItemId":1,"extendedStatus":{"playerState":"LOADING","media":{"contentId":"http://10.100.110.5:33053/","contentType":"audio/wav","streamType":"BUFFERED","metadata":{"type":0,"metadataType":0,"title":"Desktop Audio Streamer","images":[]},"mediaCategory":"AUDIO"},"mediaSessionId":5},"repeatMode":"REPEAT_OFF"}],"requestId":0}

in [4:09:09 PM] [192.168.1.107:8009] [Idle]: {"requestId":16,"type":"LOAD_FAILED","detailedErrorCode":104,"itemId":1}

in [4:09:09 PM] [192.168.1.107:8009] [LoadFailed]: {"type":"MEDIA_STATUS","status":[{"mediaSessionId":5,"playbackRate":1,"playerState":"IDLE","currentTime":0,"supportedMediaCommands":12303,"volume":{"level":1,"muted":false},"currentItemId":1,"idleReason":"ERROR"}],"requestId":0}

in [4:09:09 PM] [192.168.1.107:8009] [Idle]: {"requestId":0,"status":{"applications":[{"appId":"CC1AD845","appType":"WEB","displayName":"Default Media Receiver","iconUrl":"","isIdleScreen":false,"launchedFromCloud":false,"namespaces":[{"name":"urn:x-cast:com.google.cast.cac"},{"name":"urn:x-cast:com.google.cast.debugoverlay"},{"name":"urn:x-cast:com.google.cast.media"}],"sessionId":"6817002a-73bd-433a-9101-4fbae7a241dc","statusText":"Default Media Receiver","transportId":"6817002a-73bd-433a-9101-4fbae7a241dc","universalAppId":"CC1AD845"}],"userEq":{},"volume":{"controlType":"attenuation","level":0.699999988079071,"muted":false,"stepInterval":0.05000000074505806}},"type":"RECEIVER_STATUS"}

Check For Silence: 2,411024

Check For Silence: 3,4012399

Check For Silence: 4,4089152

Check For Silence: Send Silence (0,0245919)

out [4:09:14 PM][192.168.1.107:8009] [Idle]: {"requestId":17,"type":"GET_STATUS"}

in [4:09:14 PM] [192.168.1.107:8009] [Idle]: {"requestId":17,"status":{"applications":[{"appId":"CC1AD845","appType":"WEB","displayName":"Default Media Receiver","iconUrl":"","isIdleScreen":false,"launchedFromCloud":false,"namespaces":[{"name":"urn:x-cast:com.google.cast.cac"},{"name":"urn:x-cast:com.google.cast.debugoverlay"},{"name":"urn:x-cast:com.google.cast.media"}],"sessionId":"6817002a-73bd-433a-9101-4fbae7a241dc","statusText":"Default Media Receiver","transportId":"6817002a-73bd-433a-9101-4fbae7a241dc","universalAppId":"CC1AD845"}],"userEq":{},"volume":{"controlType":"attenuation","level":0.699999988079071,"muted":false,"stepInterval":0.05000000074505806}},"type":"RECEIVER_STATUS"}

Stream format set to Pcm 48000 16 bit

[4:09:19 PM] [192.168.1.107:8009] ResumePlaying

</p>
</details>

**Comment by SamDel** [comment]
Glad it's resolved.
The error response '"LOAD_FAILED" and "detailedErrorCode":104 ' suggest that the device couldn't connect to DAS.

I'm closing this one.
