### ISSUE TITLE
"Check firewall"-issue when using ProtonVPN

### ISSUE THREAD

**Issue by Alucard712** [SamDel/ChromeCast-Desktop-Audio-Streamer#156]
Is there any way to get it to work while being connected to ProtonVPN?

All is fine as long Proton is not connected. I already tried to white-list ChromeCast.Desktop.AudioStreamer.exe via Split Tunneling, but that did not change anything.

Besides, https://github.com/matbee-eth/chromecast-audio-stream does work with Proton, but I am missing some features with this one :-(

Edit: I tried white-listing dotnet.exe as well, but that did not change anything, either.

**Comment by SamDel** [comment]
The application tries to connect to the ip of the device when you want to start streaming. When using VPN it looks for the ip on the VPN network (not the local network).

I'm not an expert there but maybe this works: [https://community.spiceworks.com/how_to/113798-accessing-local-network-resources-while-using-vpn](https://community.spiceworks.com/how_to/113798-accessing-local-network-resources-while-using-vpn) !?

**Comment by Alucard712** [comment]
Hi, thanks for your reply.

Sadly, the options mentioned in the linked article are no longer available. It is 9 years old...

Instead, I brute-forced myself through all Proton settings, more or less randomly. In the end changing the protocol type to UDP did the trick, nothing else was needed. I am kind of a network-settings-noob, so I do not know why, but it does work at the moment.

**Comment by SamDel** [comment]
I just tried: Installed ProtonVPN with a free account, pressed 'Quick Connect' to connect to a vpn. 

For me the application worked as expected after being connected to the vpn. I tested streaming (for 5 minutes during this test) and discovery. I also tried to change the protocol from Smart to OpenVPN - TCP, and to OpenVPN - UDP.

What goes wrong for you exactly? Can you post the log?

**Comment by Alucard712** [comment]
Well, this makes me look rather stupid...

Yesterday I got so frustrated with this, that I stopped trying and de-installed the Streamer and reset Proton to my original settings.

I gave it another try today after I read your last post and everything worked fine right away. I have no f***ing idea what is different now and what my problems were on the first attempt.

I really (really!) hope that I keeps working, but if it fails again, I will post the log here.

**Comment by SamDel** [comment]
😃 

Please let it know, also when it's still working in a week or two!

**Comment by Alucard712** [comment]
Damn, here we go again. It stopped working yesterday and I could not recover it for now. Log file from today attached...

[Log_Alucard_230116.txt](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/13953535/Log_Alucard_230116.txt)

**Comment by SamDel** [comment]
There are two types of connections with this application:

1. connections from the application to the devices to send control and status messages
2. connections from the devices to the application to load the stream

For the first it looks like it works fine in the first part of the log, but at the end the connection is lost. The incoming connections from the device to load the stream fail somehow, that when you get the firewall state.

The VPN is active all the time I assume!?

**Comment by Alucard712** [comment]
Correct, VPN was active all the time.

When using the Windows Spotify App all is fine even with running VPN. So, I am afraid, this issue is somewhat Streamer-specific.

I can try again to white-list certain EXEs or IPs via split-tunneling - but I need to know which ones. (As I already wrote the obvious candidates did not improve anything.)

**Comment by Alucard712** [comment]
Spotify: Ah, alright, makes sense.

IPs: I tried 192.168.178.37 before with no effect, but together with 10.2.0.2 it does work at the moment - hope this was the solution. I will keep you updated. Thanks so far :-)

**Comment by SamDel** [comment]
In your setup the device (192.168.178.37) should connect to the application (10.2.0.2), that was were it went wrong. So 10.2.0.2 should be excluded. Hope it keeps working!

**Comment by Alucard712** [comment]
It is still working since white-listing 10.2.0.2. Besides, the device's own IP (..37 in my case) does not need to be white-listed.

**Comment by SamDel** [comment]
Nice! Thanks for letting it know.
I've [added a line](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/wiki#problems-when-using-vpn) in the wiki about it.
