### ISSUE TITLE
name of config file changed, but documnentation still points to old name?

### ISSUE THREAD

**Issue by phreich9** [SamDel/ChromeCast-Desktop-Audio-Streamer#161]
Hi,
First off, let me say "thank you" for developing and maintaining this useful little package!  I've been using it for several years now.

I discovered this documentation issue when I changed my router and it changed the IP address of my chromecast audio.  I wish I could set a permanent manual IP address for the chromecast audio, but there seems to be no way to do it.  So I am stuck relying on the router to maintain the same IP address for it, which, of course, breaks when the router is changed.

I found that there were two config files in the program directory one named : ChromeCast.Desktop.AudioStreamer.exe.config, which is the one mentioned in the documentation, and another named ChromeCast.Desktop.AudioStreamer.dll.config.  I found that I had to change the .dll.config file to get the program to find the chromecast audio at the new address.

You might want to consider changing the documentation to reflect this, as others might not notice that both now exist.
Thanks again,
Philip

**Comment by SamDel** [comment]
Thank you. I didn't notice but it must be due to a change of the platform (.Net 5/6/7 or 8).
I changed it in the [Wiki](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/wiki#configuration).

Your device should be found automatically, even if the IP changes. If not, the config file is the right place to add it.

**Comment by phreich9** [comment]
> Thank you. I didn't notice but it must be due to a change of the platform (.Net 5/6/7 or 8). I changed it in the [Wiki](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/wiki#configuration).
> 
> Your device should be found automatically, even if the IP changes. If not, the config file is the right place to add it.

Yeah, I've never been able to have it find the chromecast audio by itself on my wired network.  I've always had to add it to the config file.  Any suggestions to have it "find" it automatically?

Thanks,
Philip

**Comment by phreich9** [comment]
Since you updated the wiki, we may as well close this.....

**Comment by SamDel** [comment]
To find it automatically you must be on the same WIFI network as the device. I didn't try but you can try to add a connection on your PC to the same WIFI network as the device.

Thanks for closing.

**Comment by phreich9** [comment]
That's interesting.  I have my chromecast audio hooked up to my wired network via a USB dongle, because I prefer to connect devices via the wired network whenever possible.  My computer is also connected via a wired connection to the same network.  Is it possible that the windows firewall could be blocking the network discovery being done by your program, but is not blocking a direct connection via an IP address?  Would I look for your program's name in the firewall, or are you calling a system function to do the network discovery?

**Comment by SamDel** [comment]
You can try the things mentioned [here](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/wiki#chromecast-devices-are-not-found).

It can be the firewall, see [here for an old issue](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/issues/37#issuecomment-481156136) and solution:
```
Turn off the firewall temporary to check if it's blocking the discovery packages.
```

Or the settings in the router:
``` 
Check if the router isn't blocking discovery packages. UPnp (or MDNS, or multicast, or IGMP) should be enabled.
```
