### ISSUE TITLE
Improve group support

### ISSUE THREAD

**Issue by SamDel** [SamDel/ChromeCast-Desktop-Audio-Streamer#28]
Technically:
Now when a group has elected a new leader the device box is removed from the user interface and a new one is created. A group should not be removed from the user interface, when there's a new leader the underlying IP address should be changed. When a connection to the leader can't be made the box should turn red. Etc.

User interface:
Change the appearance of the boxes to distinguish between groups and devices.
Show (in the device box) which groups a device is member of, group 1 yellow dots/lines, group 2 orange, etc. Something like that.

**Comment by FA-Bubba** [comment]
Showing Associated Group Names on the Device Box could get cumbersome (think about where a speaker is in multiple groups, and some groups overlap...).  In this example (below) showing just two Group Names is already crowded:  

![devicebox](https://user-images.githubusercontent.com/4895674/52298688-92977500-2951-11e9-932b-ca7d924fe149.jpg)

**Comment by GrahamDLL** [comment]
> 
> 
> Showing Associated Group Names on the Device Box could get cumbersome (think about where a speaker is in multiple groups, and some groups overlap...). In this example (below) showing just two Group Names is already crowded:
> 
> ![devicebox](https://user-images.githubusercontent.com/4895674/52298688-92977500-2951-11e9-932b-ca7d924fe149.jpg)

I agree.  My vote is to keep it simple.  It is not likely that folk will have more than about six or eight speakers and not many groups.  I can remember which device is in each of my groups.

I would like to see groups and speakers appear differently in the display ... heavy borders on groups or whatever.

Maybe a future version could have a "Manage tab that allows devices to be added to groups and all that.

**Comment by GrahamDLL** [comment]
> 
> 
> Technically:
> Now when a group has elected a new leader the device box is removed from the user interface and a new one is created. A group should not be removed from the user interface, when there's a new leader the underlying IP address should be changed. When a connection to the leader can't be made the box should turn red. Etc.
> 
1.9.49

Started software .. waited a while without starting streaming ... device names still muddled ... screenshot and log attached.

Started streaming and waited and waited and waited and device names never did sort themselves out.

![capture02](https://user-images.githubusercontent.com/8915072/52340920-047ec580-2a09-11e9-80c7-8e75d29e7e8b.JPG)

[log004.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/2836279/log004.zip)

**Comment by SamDel** [comment]
I had someting like this in my mind:
![image](https://user-images.githubusercontent.com/25846417/52343941-ce960d00-2a19-11e9-964f-a0addd707a92.png)
A little coloured dot and if you hover it the group name appears. But, I agree, it's not an important feature.

**Comment by FA-Bubba** [comment]
I disagree with the comment: " **_It is not likely that folk will have more than about six or eight speakers and not many groups._**"...

I already have 6 speakers set up for testing, and after the App evolves, I plan to add about a dozen more; after all, "Multi-Room" audio is the goal, as well as adding outside speakers.  This approach may test if there is an upper limit to the number of speakers...

In any event, I believe the design of the Device Window, and the individual Device Boxes should consider future potential for a lot of speakers, and a lot of groups.  HOWEVER, I agree it is more important NOW to focus on the operation, stability and other technical issues, while keeping in mind future potential for presentation details.  For example, the Device Boxes seem to be populating in alphabetical order by Device Name -- one future enhancement could be a method to enable re-arranging the Device Boxes to a custom ordering, which would be restored each time the App is loaded.

Ideas like this, and many others could be incorporated in the future, many versions down the road...
