### ISSUE TITLE
No IP addresses found on your device.

### ISSUE THREAD

**Issue by pr0t3us** [SamDel/ChromeCast-Desktop-Audio-Streamer#38]
Facing a strange issue on my windows laptop:
![screenshot](https://user-images.githubusercontent.com/1947850/56077323-6b42a580-5de3-11e9-9f9c-7e530f970bbe.png)

Log window:

> Add IP4 addresses: 
> 
> Set size, height: 550 width: 850
> 
> No IP addresses found on your device.
>

**Comment by SamDel** [comment]
Strange. Does it happen every time, or only once?
And if you open a command prompt, and are there ip addresses when you run 'ipconfig'

**Comment by pr0t3us** [comment]
Every time. `ipconfig` is showing several network adapters including `Wireless LAN adapter` together with the virtual ones.

**Comment by SamDel** [comment]
The application uses all IP4 addresses that are not [down](https://docs.microsoft.com/en-us/dotnet/api/system.net.networkinformation.networkinterface.operationalstatus?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Net.NetworkInformation.NetworkInterface.OperationalStatus);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.5.2);k(DevLang-csharp)%26rd%3Dtrue&view=netframework-4.7.2), that are not [loopback ](https://docs.microsoft.com/en-us/dotnet/api/system.net.networkinformation.networkinterface.networkinterfacetype?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Net.NetworkInformation.NetworkInterface.NetworkInterfaceType);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.5.2);k(DevLang-csharp)%26rd%3Dtrue&view=netframework-4.7.2)and that do have [gateway addresses](https://docs.microsoft.com/en-us/dotnet/api/system.net.networkinformation.ipinterfaceproperties.gatewayaddresses?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Net.NetworkInformation.IPInterfaceProperties.GatewayAddresses);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.5.2);k(DevLang-csharp)%26rd%3Dtrue&view=netframework-4.7.2). Somewhere that goes wrong with your setup.

In [2.1.1](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/3076322/Setup.2.1.1.zip) the check on gateway addresses is removed when there are no addresses found. Can you try?

**Comment by pr0t3us** [comment]
2.1.1 Doesn't show any gui or tray icon, but it is in memory (I've tried on two systems)

**Comment by SamDel** [comment]
Sorry for creating an infinite loop for your situation, and thanks for the patience.

In [2.1.2](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/3088242/Setup.2.1.2.zip) all IP addresses found on your desktop are in the dropdown list. Can you try if there's one that's working for you? I also added logging with the network information to the log tab.

**Comment by pr0t3us** [comment]
Wow, thank you. 2.1.2 works as expected: All network cards are listed and all cast devices found 👍

**Comment by SamDel** [comment]
Nice 😃! I'm filtering the IP addresses because it makes no sense to show network interfaces that are down, etc.
Now I'm curious why they didn't show up at first. Are the IP addresses not in the local ip ranges? Can you post some of the network interface logging I added? (Especially from the network card your using!)

**Comment by pr0t3us** [comment]
Sure, that's the network card I'm using:

```

Name networkInterface: Wi-Fi 2

Address: fe80:**************

Address family: InterNetworkV6

Operational status: Up

NetworkInterface type: Wireless80211

GatewayAddresses count: 1



Address: 192.1**************

Address family: InterNetwork

Operational status: Up

NetworkInterface type: Wireless80211

GatewayAddresses count: 1

```

**Comment by SamDel** [comment]
Thanks, for me it looks exactly the same.

Are you using the 'Start application when Windows starts' option? Maybe the wifi wasn't up when the application started, and something goes wrong adding the IP addresses later.

**Comment by pr0t3us** [comment]
> 'Start application when Windows starts' option

I just started it manually. Anyway 2.1.2 works 👍
