### ISSUE TITLE
Command line or config to change sound source?

### ISSUE THREAD

**Issue by OneBobone** [SamDel/ChromeCast-Desktop-Audio-Streamer#42]
Very interesting project!
I am curious if there is a way to change the settings for the sound source more or less programatically?
Also, would you kow if it is possible to select individual pairs in 5.1 sound cards?
Windows7

**Comment by SamDel** [comment]
Thanks. 

Changing the recording device programmatically is not really supported. But the configuration (with the RecordingDeviceID) is stored in the file below. You can try to change it there!
`C:\Users\<username>\AppData\Local\ChromeCast\ChromeCast.Desktop.AudioS<random>\<version>\user.config
`

I don't know about individual pairs in 5.1 sound cards. Aren't they listed in the recording dropdown?

**Comment by OneBobone** [comment]
Thanks, I had a look at the config file. I found this: 
`            <setting name="RecordingDeviceID" serializeAs="String">
                <value>{0.0.0.00000000}.{13797e4c-9a87-4a04-be23-e456d8966eea}</value>`
But, it does not change when I change source?

**Comment by SamDel** [comment]
The settings are persisted to the user.config file when you close the application, and loaded when you start the application. There's no hook on the config file to load the changes when the application is running!

When you change the RecordingDeviceID in the config file when the application is closed, the new recording device should be used when you start the application.

I don't think it's possible then to select an individual pair. The application gets all possible recording devices from Windows. I'll have a look at it later.
