### ISSUE TITLE
Devices not found after an update of the Chromecast firmware

### ISSUE THREAD

**Issue by c64droid** [SamDel/ChromeCast-Desktop-Audio-Streamer#47]
Hi. Just discovered this and trying it out - looks promising, but it doesn't find all of my Chromecast Audio devices.  The log (attached below) shows some object reference errors...

[DeviceInformation.GetDeviceInformation] Object reference not set to an instance of an object.

My setup is as follows:  5 x chromecast audio devices with IP addresses .32 to .36, with 2 groups configured (one for whole house, one for just a pair of them).  I've tried temporarily disabling my firewall, and also manually entering one of the missing ones in the config file, but they still don't appear.  Please let me know if you need any more info to help debug.

Thanks.

[DesktopAudioStreamer.log](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/3341674/DesktopAudioStreamer.log)

**Comment by SamDel** [comment]
Can you try if you can get the device information with these links:

[192.168.1.32](http://192.168.1.32:8008/setup/eureka_info?params=version,audio,name,build_info,detail,device_info,net,wifi,setup,settings,opt_in,opencast,multizone,proxy,night_mode_params,user_eq,room_equalizer&options=detail)
[192.168.1.33](http://192.168.1.33:8008/setup/eureka_info?params=version,audio,name,build_info,detail,device_info,net,wifi,setup,settings,opt_in,opencast,multizone,proxy,night_mode_params,user_eq,room_equalizer&options=detail)
[192.168.1.34](http://192.168.1.34:8008/setup/eureka_info?params=version,audio,name,build_info,detail,device_info,net,wifi,setup,settings,opt_in,opencast,multizone,proxy,night_mode_params,user_eq,room_equalizer&options=detail)
[192.168.1.35](http://192.168.1.35:8008/setup/eureka_info?params=version,audio,name,build_info,detail,device_info,net,wifi,setup,settings,opt_in,opencast,multizone,proxy,night_mode_params,user_eq,room_equalizer&options=detail)
[192.168.1.36](http://192.168.1.36:8008/setup/eureka_info?params=version,audio,name,build_info,detail,device_info,net,wifi,setup,settings,opt_in,opencast,multizone,proxy,night_mode_params,user_eq,room_equalizer&options=detail)

Let me know!

**Comment by c64droid** [comment]
Hi. Thanks for the quick response.  I can get the device information response in a browser ok, and the software does too.  I've actually installed VS to try and debug this and attach the details of where it's going wrong below.  Appears to be the JsonConvert.DeserializeObject function isn't pulling all the values from the response into the required structure.

[DesktopAudioStreamer debug.txt](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/3341775/DesktopAudioStreamer.debug.txt)

Don't know why it managed it for 2 devices before, but now it's failing here on all 5 of my devices.

**Comment by SamDel** [comment]
Thanks, good info!

It's looks like the chromecast devices are updating right now to a newer version just now.
I have a couple of devices that are on version=8 that are still appearing in the application. 
And a couple have version=10 that don't appear anymore.

I'll have a look if I can add support for version=10!

**Comment by c64droid** [comment]
Ah that makes sense now.  I had turned off the 2 devices that **_were_** found to see if any of the others appeared, and when I turned them back on they no longer appeared.  They must have updated to v10 when I restarted them.  So I assume the v10 ones are returning extra/different info that your code doesn't expect. I look forward to the updated version.
Thanks again.

**Comment by SamDel** [comment]
Version [2.3.2](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/3341871/Setup.2.3.2.zip) has support for version=10 devices. There's no groups support yet!

Can you try?

**Comment by c64droid** [comment]
Yes, it has found all my devices and I can cast to them all, thanks.  Obviously without the Groups support I can only sensibly cast to one at a time as they're all out of sync. :-)
Are you planning to include Groups support at some point?

**Comment by SamDel** [comment]
Thanks! Yes, it looks like I can add it later on.

Group information is removed from the version=10 device information so I have to change some things.

**Comment by SamDel** [comment]
Can you try if groups work for you in [Setup 2.3.3.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/3341938/Setup.2.3.3.zip)?

**Comment by FA-Bubba** [comment]
I am running v2.3.1 of the Streamer, and after a PC reboot, the Streamer only sees 1 (the Home Hub) of my 9 devices (1 Home Hub, 2 Minis, and 6 Chromecast Audios...  Prior to the reboot, the Streamer was streaming to ALL of them via an audio Group that has all of the devices in it.  The Hub, Minis and All of the Chromecast devices are at Cast Firmware version 1.40.156414.

What could have caused this?  (Log & Screenshot attached)

[Log-2019-06-29-v2-3-1-SpeakersNotFound.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/3341942/Log-2019-06-29-v2-3-1-SpeakersNotFound.zip)

**Comment by SamDel** [comment]
That's probably the same issue. The Chromecasts are updating to a new version, the device information the application receives changed completely.
Setup 2.3.3 (see above) has support for the new version. Can you try?

**Comment by FA-Bubba** [comment]
I saw your v2.3.3 post after I posted my previous comment.  I've installed v2.3.3, and it is finding ALL devices & Groups.

Thank you!

This raises a question, though, the previous comments above reference "Chromecast version 10" -- when I view the device details on the Google Home App, it shows my Chromecast devices are at "Cast firmware version 1.40.156414"....    What is the relationship of this to "Version 10"?

**Comment by SamDel** [comment]
The previous version was (for me, from the device information): 
```
"version": 8
"cast_build_revision": "1.28.102057"
```
The one that installed today is:
```
"version": 10
"cast_build_revision": "1.40.156414"

```

So it looks like version 10 (consumer version?) is the same as 1.40.156414 (build version?)

**Comment by FA-Bubba** [comment]
OK...  I haven't found a reference to "version 10" anywhere, but I may not be looking in the right place.  Two of my Chromecast Audio devices are about 6 months old, purchased just after Google announced they were discontinuing the product.  I have since purchased 8 more, from various sources.  I noticed at the beginning of this week that they mostly had different Cast versions (1.37....  1.39....  &  1,40....).  Yesterday, I powered them Off, then On to force the updates, and as of last night, all were on version 1.40.156414

Interesting to note from your observation that these were then on "Version 10", but still working with Streamer version 2.3.1 (until my PC rebooted this morning)...    Now all working fine with Streamer Version 2.3.3.

It isn't clear if the Chromecast Audios will update on their own, or if they need to be powered Off/On to force the update.  (The setup instructions mention that at power-up, they will be in "update mode" for 3 to 10 minutes.)  Also, it isn't clear if Google will continue to issue updates, but my gut feeling is "yes", because the Google Home Hubs, and the Minis are using this same Cast version, and if they update the firmware for those devices, then the Chromecast Audios should be able to update as well (unless Google writes code that inadvertently 'bricks' the Chromecast Audio)...

**Comment by c64droid** [comment]
Groups are working for me now thanks.  Is it normal that there's a massive delay (~15s from starting/stopping music on PC before it starts/stops on speakers)?

**Comment by FA-Bubba** [comment]
That seems to be typical of what I have experienced from when I first started using this in January...

**Comment by SamDel** [comment]
Indeed, the delay is normal behaviour. It's the buffer on the device, and dependent on the stream format you choose on the options tab. 
From the [wiki](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/wiki):

`Mp3 320 kbps is default. Wav is lossless but takes a lot of network bandwidth. Mp3 128 kbps takes the least network bandwidth.
`

Select Wav for the least delay!

**Comment by c64droid** [comment]
Great thanks, just a short delay using WAV.  Many thanks for your prompt fixes, much appreciated.  Keep up the good work.  :-)

**Comment by FA-Bubba** [comment]
For what it is worth, I am less concerned about the delay between the PC and the speakers than I would be if the various speakers get out of sync.

Your tip to use Groups to ensure all speakers are in sync has been working very well for me...

**Comment by FA-Bubba** [comment]
If the source is from local MP3 files, what would be the benefits (if any) of using WAV as the stream format?

**Comment by SamDel** [comment]
Reopening this one, there are probably other people with the same issue. Please upgrade to [2.4](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/releases) if so!

**Comment by FA-Bubba** [comment]
I posted this elsewhere:  My PC is complaining about invalid file dates on the 2.4 files (they are in the future).

**Comment by SamDel** [comment]
When you're playing an MP3 file it's decoded first when you play it. When you have WAV selected it's not encoded again to MP3 before streaming to the devices, with MP3 as stream format it is encoded again. 

I don't know if the quality decreases in this scenario if the stream is encode again!

**Comment by SamDel** [comment]
Is the firewall complaining about it? I think it's due to different time zones!

**Comment by FA-Bubba** [comment]
Actually, the Date-Time of the ZIP file was NOT in the future, but the files inside the ZIP were...
Both files:  06/29/2019 5:29 PM
ZIP:  06/29/2019 12:30 PM

I don't believe it is a time-zone issue, though, this usually happens when a file creation tool is out of sync with Universal Time.

Sometime this evening, after 5:29 PM, it won't be an issue...

The 'future' date was flagged by a Peer-2-Peer program I use to sync files across 4 PCs (Resilio Sync) -- it a great utility to duplicate folder contents in real time.
