### ISSUE TITLE
Feature: Don't reconnect to devices if another source is already casting to them

### ISSUE THREAD

**Issue by dday4thedeceiver** [SamDel/ChromeCast-Desktop-Audio-Streamer#51]
This is to facilitate casting from other sources without DAS taking over immediately. 

(I understand this will not achieve its purpose 100% as Google doesn't always terminate the cast on a Stop command through the assistant but it will help in other situations)

**Comment by SamDel** [comment]
The application checks if an other application is playing before automatically restarting the stream.
Doesn't it work for you? In which scenario?

**Comment by dday4thedeceiver** [comment]
Upon looking closer, this works well with a single device. The issue is different and is with groups. I'll create another entry

**Comment by dday4thedeceiver** [comment]
https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/issues/53
