### ISSUE TITLE
Connect to Chromecast doesn't mute desktop speaker

### ISSUE THREAD

**Issue by Hauru14** [SamDel/ChromeCast-Desktop-Audio-Streamer#56]
Hi ! 

I received my Chromecast today and when i tried cast from my laptop (with Chromecast in chrome, ChromeCast Desktop Audio Streamer, or other), the sound is controlled by my laptop mixer, so i have sound on my TV and my laptop, this is very annoying because when i mute my laptop, i mute Chromecast too.. 
I've tried a bit of things but no one solved my problem. Did someone fix that ? 
(Running in win10, have the same Wi-Fi connection for both laptop and chromecast)

**Comment by GrahamDLL** [comment]
> 
 so i have sound on my TV and my laptop,
>

There should be a Auto-mute desktop audio tickbox on the Options tab

**Comment by Hauru14** [comment]
> > so i have sound on my TV and my laptop,
> 
> There should be a Auto-mute desktop audio tickbox on the Options tab

Yeah i saw this option. But this is doing the same things, when my laptop is muted (manually or with the option), the soft doesn't have sound (dB bar stay at zero)

**Comment by GrahamDLL** [comment]
> 
> 
> > There should be a Auto-mute desktop audio tickbox on the Options tab
> 
> when my laptop is muted (manually or with the option), the soft doesn't have sound (dB bar stay at zero)

It should be ... Do not use the mute on the laptop ... the audio on the laptop should be auto muted when you start DAS.  Is that what is happening?

**Comment by Hauru14** [comment]
> Do not use the mute on the laptop ... the audio on the laptop should be auto muted when you start DAS. Is that what is happening?

Yes, i tick th option, and when i start to cast music, my laptop is muted, but sound on my tv starts, and few second after, is muted. The problem is (i think) that i'm sending no sound, the recording device in the option is Realtek (speaker on my laptop) but when the sound is muted (with the option or manually) this recording device is sending no sound ...

**Comment by GrahamDLL** [comment]
> 
> 
> > Do not use the mute on the laptop ... the audio on the laptop should be auto muted when you start DAS. Is that what is happening?
> 
> Yes, i tick th option, and when i start to cast music, my laptop is muted, but sound on my tv starts, and few second after, is muted. The problem is (i think) that i'm sending no sound, the recording device in the option is Realtek (speaker on my laptop) but when the sound is muted (with the option or manually) this recording device is sending no sound ...

On the Options tab ... tick the box Log Device Communication ... Restart DAS and recreate the problem ... Copy and Paste everything in the Log tab into Notepad and save the log and attach it to a post.  Somebody will be along soon to look at the logs.  Thank you.

**Comment by SamDel** [comment]
I think the answer is somewhere in the system settings or setup. I don't know where it goed wrong.

- Do you have multiple entrien in the 'Recording device' dropdown? Which ones?
- Check the Realtek device properties.
- How's the Volume Mixer for you? 

![image](https://user-images.githubusercontent.com/25846417/64068863-a2084380-cc3e-11e9-8ca2-d56317778824.png)

**Comment by SamDel** [comment]
Still the same issue for you @Hauru14 ?
