### ISSUE TITLE
Version 2.5 not recognizing chromecast device

### ISSUE THREAD

**Issue by AndyIreland** [SamDel/ChromeCast-Desktop-Audio-Streamer#65]
Version 2.5 not recognizing my chromecast device - not even after 'scan again for devices' or changing ip4 address used 

but earlier audio-cast-win32-ia32 build does 

![desktop audio streamer](https://user-images.githubusercontent.com/49172217/70101951-8aba6700-162e-11ea-9b44-72f7a3adcd49.jpg)

**Comment by SamDel** [comment]
Can you check if MDNS/multicast is enabled in your router?

You can also [add the IP of the Chromecast device in the .config file](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/wiki#configuration).
