### ISSUE TITLE
[Request] 192Khz lossless streaming

### ISSUE THREAD

**Issue by wolf-hg** [SamDel/ChromeCast-Desktop-Audio-Streamer#66]
Could this be possible given good enough processing power and network? The ability to select a specified sound card for it to stream gives a lot of possibilities for signal processing with virtual cables and such. One thing I would like to try is to run an FM transmitter with signal processing and stereo MPX signal generation. It requires at least 176.4Khz sampling rate for it to work. The Chromecast Audio internal DAC seems to support it, would it accept a higher rate?

**Comment by SamDel** [comment]
I thinks it's possible. This [test version](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/3940251/Setup.2.5.7.zip) ignores the selected stream format and uses 176400.

Can you try?

**Comment by wolf-hg** [comment]
With stream format set to wav it still seems to be 44.1Khz. It drops off at 22Khz just above the pilot tone.

**Comment by wolf-hg** [comment]
I'm guessing it won't work since it is such a niche setup. Is there a way to see the active format the device is using?

**Comment by wolf-hg** [comment]
Did some more testing, reset the device and reinstall etc. Using a sweep generator I was able to get it to produce 96Khz (48x2) before it started re-sampling the signal. So while it might not do more then that, it works with 96 which should be more than enough for any regular Hi-res streaming.

**Comment by SamDel** [comment]
You're right, the test version isn't 176400. I think I have to resample the stream in the application then, but I don't think there's an easy way to do it.
