### ISSUE TITLE
Minimize to Tray button .. missing?

### ISSUE THREAD

**Issue by starfishpatkhoo** [SamDel/ChromeCast-Desktop-Audio-Streamer#69]
First off, WOW on this superb application! It's wonderful, brilliant, works perfectly, exactly what I need! I use it to stream from MusicBee on my desktop PC to four Google Chromecast/Home devices in three rooms. #BeatThatSonos ! Ha ha ha!

Secondly, I think in Issue #46 there was mention about click on the button to minimize to sys tray.. Unfortunately, in 2.6 I can't seem to find the button. Ha ha ha! I must be blind, right? ^_^

Thirdly, I'm a programmer and so I will endeavour to grab the source, have a look, and try to help out. This is just brilliant and you've made my house sound great.

**Comment by SamDel** [comment]
Thanks! The button is in the systray:

![image](https://user-images.githubusercontent.com/25846417/71705534-97bea780-2de0-11ea-9118-02a275541f09.png)

- (Left) Click it to show/hide the window
- Right click it to show the lis of devices

**Comment by starfishpatkhoo** [comment]
Ah! Okie! Cool, thank you! I was looking for a button on the main window.. And I tried double clicking the systray icon.. But I got that. Thank you! ^_^

**Comment by FA-Bubba** [comment]
I was experiencing a lot of drop-outs (v2.6.0), so I clicked the "Reset Settings" button.  The drop-outs persisted, so I did "Reset Settings" again, and repeated this action several times, but the drop-outs continued, and eventually, the Stream never restarted, but just displayed "Buffering" in the selected Device boxes.

Finally, I decided to close DAS, and right-clicked the System Tray icon.  The List of Devices was repeated several times (I am assuming once for each click on "Reset Settings").  I then closed DAS by clicking the "X" in the upper right corner.

I then restarted DAS, and it seems to be back to 'normal'...

Evidently, clicking "Reset Settings" does not clear the list from the System Tray icon, and the LONG, redundant list prevents streaming.

**Comment by SamDel** [comment]
That's the same issue as [GrahamDLL reported](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/issues/60#issuecomment-569713818).

Should be fixed in [2.6.1](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/4020269/Setup.2.6.1.zip)
