### ISSUE TITLE
Can you stream more than 1 mp3 file at a time?

### ISSUE THREAD

**Issue by thepuckguy** [SamDel/ChromeCast-Desktop-Audio-Streamer#73]
I found this site after searching for a way to play mp3's I have on my computer in My Music to my Google Home devices. I found I can copy and past the file into Chromes address bar but I can only play 1 song at a time. Does this streamer allow to send and play multiple mp3 files?

Thank you,
Dave

**Comment by FA-Bubba** [comment]
Hi Dave,
The DAS will cast any music that is sourced on your PC,  I use iTunes to catalog my MP3 Library, and to make PlayLists.  You can use just about any App that plays from your MP3 collection, like WinAmp, MS Media Player, VLC Media Player, Groove Music, ..., etc.  Just Google "Windows MP3 Player" to get a list of Apps.  

Cheers!

**Comment by thepuckguy** [comment]
Mr Bubba,

Thanks for the quick response! I just use MS Media Player so I'm golden!

**Comment by ablazhov** [comment]
Can MS Media Player play more than 1 music file at a time?

**Comment by thepuckguy** [comment]
Yes it can and I'm streaming multiple songs as we speak! It works great, exactly what I was looking  for!
