### ISSUE TITLE
Feature Request: Minimize to tray

### ISSUE THREAD

**Issue by oucil** [SamDel/ChromeCast-Desktop-Audio-Streamer#74]
I do a ton of app switching while working, and the fewer open windows I have the better to keep the clutter down, would really appreciate being able to "close to tray" or "minimize to tray".

I should mention, it seems like the app is supposed to have this, but when I close it, the audio snaps back to my pc.  Bug or intentional?

Thanks!

**Comment by SamDel** [comment]
You can (left)click the systray icon to show/hide the window (minimize to tray). And there's an option to 'Show window at startup'.

**Comment by Ben-Ledoux-Drexel** [comment]
Just started using it and really loving it, I was wondering though if it would be possible so that when you close the window it is automatically minimized to the tray

**Comment by FA-Bubba** [comment]
When I click the small horizontal line in the upper right corner of the window, it does indeed minimize to the SystemTray.

**Comment by SamDel** [comment]
In [2.9.1](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/4686452/Setup.2.9.1.zip) I added an option to 'Minimize to tray when closing'.

**Comment by oucil** [comment]
Super @SamDel, thanks for implementing that, I'll give it a test asap.

**Comment by JpTiger** [comment]
Thanks for adding! Is there a reason 2.9.1 isn't on [the Releases page](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/releases)?

**Comment by SamDel** [comment]
I'll create a version 3.0 of it shortly!

**Comment by SamDel** [comment]
The new option is in the latest release: [Version 3.0](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/releases)
