### ISSUE TITLE
IAudioClient::Initialize caused an error: 0x8889000f, "Unknown HRESULT".

### ISSUE THREAD

**Issue by GrahamDLL** [SamDel/ChromeCast-Desktop-Audio-Streamer#75]
I click to start playing a group ... The PC speakers go silent ... No sound from the chromecast devices
[log-after-silence.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/4528810/log-after-silence.zip)

**Comment by SamDel** [comment]
Are the speakers unplugged or disabled?
[https://www.hresult.info/FACILITY_AUDCLNT/0x8889000F](https://www.hresult.info/FACILITY_AUDCLNT/0x8889000F)

> The method failed to create the audio endpoint for the render or the capture device. This can occur if the audio endpoint device has been unplugged, or the audio hardware or associated hardware resources have been reconfigured, disabled, removed, or otherwise made unavailable for use.

**Comment by GrahamDLL** [comment]
I was playing a radio station through a web browser on a laptop and I could hear the music playing through the laptop speakers.  I clicked in DAS to start casting to a Chromecast group ... the laptop speaker was muted but nothing was played by the Chromecast speakers.

I get the same result when I play music using the desktop app of the Qobuz streaming service.

I have done all of the usual stuff including re-booting the laptop and disconneting and reconnecting all of the Chromecast devices.  I am quite baffled.

I had a thought after typing the above.  I went into Device Manager and uninstalled the sound device.  I rebooted and Windows automagically re-installed the sound device and the problem went away.

But ... I have had a different problem since forever ... I click in DAS to start casting to a group and it mutes the laptop speaker, tries to cast (I sometimes hears bongs from the speakers attached to the Chromecast devices) but after a few seconds it disconnects from the Chromecast group.  A second attempt to cast usually works okay.  The attached should show all this.

Let me know if the attached is not enough.  I can usually recreate the problem.  Thanks for your help.

[log-cast-fail.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/4530070/log-cast-fail.zip)

**Comment by SamDel** [comment]
Thanks, it looks like periodically requesting the device state was interfering with loading the stream.

Can you try [2.7.2](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/4531075/Setup.2.7.2.zip)?

**Comment by GrahamDLL** [comment]
2.7.2 ... Seems to be the same ... Started DAS ... Clicked to cast to a group ... laptop speaker was muted but nothing from Chromecast devices ... Clicked to cast for a second time and music started from the Chromecast devices.  Thanks
[two-clicks.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/4533508/two-clicks.zip)

**Comment by SamDel** [comment]
The logs are different, now group 'Down' sends a 'CLOSE' message (to close the connection) immediately after the 'LAUNCH' message. I don't know why.

Is it still the same? [Setup 2.7.4.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/4542593/Setup.2.7.4.zip) has some small changes, but I don't think it helps in your case.

**Comment by GrahamDLL** [comment]
2.8

This is intermittant ... sometimes I need to click twice to start casting ... sometimes only once ... An example of two clicks is a few minutes before I copied the attached log.  Thanks for looking at this.

[two-click-2.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/4593265/two-click-2.zip)

**Comment by SamDel** [comment]
The original issue was resolved by re-installing the sound device.

The other issue is continued [here](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/issues/76).
