### ISSUE TITLE
Two clicks to start casting

### ISSUE THREAD

**Issue by GrahamDLL** [SamDel/ChromeCast-Desktop-Audio-Streamer#76]
2.8

I reported this earlier and I have now started a new thread ...

This is intermittant ... sometimes I need to click twice to start casting ... sometimes only once ... An example of two clicks is a few minutes before I copied the attached log. Thanks for looking at this.

two-click-2.zip

**Comment by SamDel** [comment]
Thanks for the nice long log file. I've seen that behaviour before, the application sends a 'LAUNCH' message to the device. The device immediately replies with 'CLOSE':

> out [2:34:52 PM][192.168.1.63:42237] [LaunchingApplication]: {"appId":"CC1AD845","requestId":6716,"type":"LAUNCH"}
> in [2:34:52 PM] [192.168.1.63:42237] [LaunchingApplication]: {"type":"CLOSE"}

I don't know why the device sends a close message immediately. The application sends the messages in the same order every time. I will look at it again later!

The option 'Automatically restart when the stream is closed' is a workaround for this behaviour. When the device sends a close message, the application just tries to launch again.

I'll close the other issue!

**Comment by GrahamDLL** [comment]
For completeness ... the automatic restart appears to work in the attached.

I can intermittantly recreate the problem ... Start casting ... close app (while casting is still in progress) ... wait 20 seconds ... start app ... start casting ... In a trivial number of tests ... this caused the problem about three times out four.

[two-clicks-auto-restart.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/4594084/two-clicks-auto-restart.zip)

**Comment by SamDel** [comment]
Thanks, good research.

You're streaming to a group. The application didn't get the status of groups after a group was added to the devices box. 

Fixed it in [Setup 2.8.1.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/4597709/Setup.2.8.1.zip). The application gets the status of a group after it's added. And I added a check when you start streaming to make sure the status of the device is received before launching.

Can you try?

**Comment by GrahamDLL** [comment]
2.8.1
Repeated the stop-start described above.  Casting began nicely about six times out of eight.  One time there seemed to be a delay before casting began that was longer than usual.  One time the first click failed to cast and a second click was required.

I am content to describe this as fixed.  The test that I am doing is not realistic use and depends upon the Chromecast devices coping nicely with unrealistic stops and starts.

I'll post again if the problem happens in more realistic use.  Thanks for all your good work.

[DAS.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/4603720/DAS.zip)

**Comment by SamDel** [comment]
Nice! Some changes in [Setup 2.8.2.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/4605614/Setup.2.8.2.zip):

- The status check was waiting forever, what caused the application to hang sometimes. Now it's waiting for maximum 2 seconds.
    > And I added a check when you start streaming to make sure the status of the device is received before launching.
- A stop message is send to devices that are playing when you close the application.

**Comment by GrahamDLL** [comment]
2.8.2

Multiple clicks failed to start casting ... this is after leaving everything idle overnight

[multiple-clicks-no start-cast.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/4616467/multiple-clicks-no.start-cast.zip)

**Comment by SamDel** [comment]
Thanks, 2.8.2 was waiting for 2 seconds for a status was received. If nothing was received the application didn't try to launch the stream.

In [Setup 2.8.3.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/4617245/Setup.2.8.3.zip):
- The application tries to launch the stream, also when no status reply is received.
- When nothing is received from a device for 15 minutes the application tries to get the status of the device again.

**Comment by GrahamDLL** [comment]
2.8.3 casts first time every time ... thank you.

**Comment by SamDel** [comment]
Nice, thanks. I'll make a version 2.9 of it.

**Comment by SamDel** [comment]
[Version 2.9](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/releases/tag/v2.9)
