### ISSUE TITLE
recognises my chromecast tv, but does not play music

### ISSUE THREAD

**Issue by peefour** [SamDel/ChromeCast-Desktop-Audio-Streamer#8]
hi,

thanks for your program.
does it work for you?

i installed it via the installer, and it recognises my chromecast tv, and even starts my tv up when my tv is in standby.
 but it does not play music. the tv shows the google slideshow, or the blue chromecast icon, but no sound.

the acidhax application does play sound without problems, but i prefer yours because it is much smaller, and has an easy installer.

how can i get it to work?

thanks!

**Comment by SamDel** [comment]
Hi, thanks for the feedback,
It works for me, together with a Chromecast Audio device connected to my stereo.
I don't have a Chromecast device for the TV, so I didn't try. Maybe I try later, I'll let you know!

**Comment by resom78** [comment]
Hi,

I confirm the issue of peefour!
The Chromecast 2 is well recognized, it starts buffering and after a couple of seconds an error occured.
Here you can find the log file if its help:

out [07:49:49][192.168.1.14]: {"requestId":3,"type":"GET_STATUS"}

out [07:49:59][192.168.1.14]: {"requestId":4,"type":"GET_STATUS"}

out [07:50:09][192.168.1.14]: {"requestId":5,"type":"GET_STATUS"}

in [07:50:15] [192.168.1.14]: {"type":"MEDIA_STATUS","status":[{"mediaSessionId":2,"playbackRate":1,"playerState":"PLAYING","currentTime":0,"supportedMediaCommands":15,"volume":{"level":1,"muted":false},"activeTrackIds":[],"currentItemId":2,"repeatMode":"REPEAT_OFF"}],"requestId":0}

in [07:50:15] [192.168.1.14]: {"type":"MEDIA_STATUS","status":[{"mediaSessionId":2,"playbackRate":1,"playerState":"BUFFERING","currentTime":0,"supportedMediaCommands":15,"volume":{"level":1,"muted":false},"activeTrackIds":[],"media":{"contentId":"http://192.168.1.10:49699/","contentType":"audio/wav","streamType":"BUFFERED","metadata":{"type":0,"metadataType":0,"title":"Desktop Stream","images":[]},"duration":null},"currentItemId":2,"items":[{"itemId":2,"media":{"contentId":"http://192.168.1.10:49699/","contentType":"audio/wav","streamType":"BUFFERED","metadata":{"type":0,"metadataType":0,"title":"Desktop Stream","images":[]},"duration":null},"autoplay":true,"activeTrackIds":[]}],"repeatMode":"REPEAT_OFF"}],"requestId":1}

in [07:50:15] [192.168.1.14]: {"type":"MEDIA_STATUS","status":[{"mediaSessionId":2,"playbackRate":1,"playerState":"BUFFERING","currentTime":0,"supportedMediaCommands":15,"volume":{"level":1,"muted":false},"activeTrackIds":[],"media":{"contentId":"http://192.168.1.10:49699/","contentType":"audio/wav","streamType":"BUFFERED","metadata":{"type":0,"metadataType":0,"title":"Desktop Stream","images":[]},"duration":null},"currentItemId":2,"items":[{"itemId":2,"media":{"contentId":"http://192.168.1.10:49699/","contentType":"audio/wav","streamType":"BUFFERED","metadata":{"type":0,"metadataType":0,"title":"Desktop Stream","images":[]},"duration":null},"autoplay":true,"activeTrackIds":[]}],"repeatMode":"REPEAT_OFF"}],"requestId":2}

in [07:50:15] [192.168.1.14]: {"type":"MEDIA_STATUS","status":[{"mediaSessionId":2,"playbackRate":1,"playerState":"IDLE","currentTime":0,"supportedMediaCommands":15,"volume":{"level":1,"muted":false},"media":{"contentId":"http://192.168.1.10:49699/","contentType":"audio/wav","streamType":"BUFFERED","metadata":{"type":0,"metadataType":0,"title":"Desktop Stream","images":[]},"duration":null},"currentItemId":2,"idleReason":"INTERRUPTED","extendedStatus":{"playerState":"LOADING","media":{"contentId":"http://192.168.1.10:49699/","contentType":"audio/wav","streamType":"BUFFERED","metadata":{"type":0,"metadataType":0,"title":"Desktop Stream","images":[]}}}}],"requestId":0}

in [07:50:15] [192.168.1.14]: {"type":"MEDIA_STATUS","status":[{"mediaSessionId":3,"playbackRate":1,"playerState":"BUFFERING","currentTime":0,"supportedMediaCommands":15,"volume":{"level":1,"muted":false},"activeTrackIds":[],"currentItemId":3,"repeatMode":"REPEAT_OFF"}],"requestId":0}

out [07:50:19][192.168.1.14]: {"requestId":6,"type":"GET_STATUS"}

ex [192.168.1.14]: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée 192.168.1.14:8009

out [07:50:30][192.168.1.14]: {"requestId":7,"type":"GET_STATUS"}

**Comment by SamDel** [comment]
Thanks for the log. I could reproduce exactly the same issue.

Chromecast TV doesn't support the stream format I used. I changed the format from WAV IEEE float / 32 bits / 48000 to WAV PCM / 16 bits / 44100.

I added a [new release](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/blob/master/Releases/Setup%200.8.zip) with the fix, can you try and let me know?

**Comment by resom78** [comment]
Hi SamDel,
Just to let you know that it works perfectly!! And the way you manage the sound latency is amazing, you're the only one who can handle a latency less than 0.5s with a chromecast.And just a question: Is there a way to start the program only in the system tray without the main window? I saw I can toggle the window but not when the app launch.
I will follow the updates regularly.
Cheers
    Le samedi 17 mars 2018 à 10:41:26 UTC+1, SamDel <notifications@github.com> a écrit :  
 
 
Thanks for the log. I could reproduce exactly the same issue.

Chromecast TV doesn't support the stream format I used. I changed the format from WAV IEEE float / 32 bits / 48000 to WAV PCM / 16 bits / 44100.

I added a new release with the fix, can you try and let me know?

**Comment by SamDel** [comment]
Thanks for letting me know. There's not an option to start in the systray yet, maybe I add one in the next release.
