### ISSUE TITLE
Lipsyncing issue on video playback

### ISSUE THREAD

**Issue by yadav26** [SamDel/ChromeCast-Desktop-Audio-Streamer#80]
I think you are using some local internal buffer to smooth stream the audio. hence there I see a problem with audio over vlc video movie playback.

**Comment by SamDel** [comment]
You can't use this tool to sync the video on your desktop with the audio on the device.
See [this issue](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/issues/27).
