### ISSUE TITLE
Offset between the sound of the pc and the sound of my connected Google speakers.

### ISSUE THREAD

**Issue by Benlge** [SamDel/ChromeCast-Desktop-Audio-Streamer#82]
Hi,

Congratulations on your work. I've been looking for a similar application for Windows for months.
My problem is the separation between the sound of the pc and that of the connected speakers, because I wanted to be able to watch my movies on my pc, and have the sound on my connected speakers. But watching a film out of sync between the image and the sound is unbelievable. It's because of the buffer isn't it? Even if the sound was correct, without interruption, by putting the slider of the '' Offset control '' to the minimum, there would still be a small offset.

Do you think that in the near future, it will be possible to no longer have an offset by operating correctly?

Best regards.

Benoit PERET - Belgium Wallonia.

**Comment by SamDel** [comment]
Thanks @Benlge. No, I don't think it will be possible in the near future. You can also read [this issue](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/issues/27) about it (When you set the stream format to wav you can get < 5 seconds lag. ).

With the [experimental lag-control](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/wiki#configuration) the audio stream is corrupted (bad sound quality), but you can get very little lag using it.

**Comment by Benlge** [comment]
Hi @SamDel,

Thank you for your answer.
But just a little out of touch, it's too much when watching a movie ...
But your app is great, because I can manage the sound of my speaker groups, and my connected speakers. Which is much easier than doing it by voice, or via Google Home, which recognizes my speakers 1 time out of 2 ...
Thank you.

Have a nice day.

Ben

**Comment by SamDel** [comment]
Nice that you like the application! I'm closing this one.
