### ISSUE TITLE
Auto execute play button if buffering / connect error

### ISSUE THREAD

**Issue by Buster14** [SamDel/ChromeCast-Desktop-Audio-Streamer#83]
I'm using latest version but i noticed sometimes the connection is still dropped, or its in "buffering" state.
But its easily solved by pressing the play button several tkmes, i was thinking it'd be great if you could integrate it into the options. 

I already checked the "automatically restart when stream is closed" but it doesnt seem to help.

**Comment by SamDel** [comment]
You're right, that's the purpose of "automatically restart when stream is closed". That option doesn't trigger when the state is [buffering or loading media or playing](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/blob/ba2aa6150a101536462f01ce2549fe2b39c36be4/Source/ChromeCast.Desktop.AudioStreamer/Communication/DeviceCommunication.cs#L254) now. Maybe this option should be fine-tuned for your situation. Can you post some logs when auto-restart doesn't work?
