### ISSUE TITLE
Please post a working configuration file with manually specified device

### ISSUE THREAD

**Issue by skyiron** [SamDel/ChromeCast-Desktop-Audio-Streamer#85]
I've looked at the documentation and at the ChromeCastDesktop.AudioStreamer.exe.config but I am confused as to how to specify it in the config file.
Could someone show a working configuration with a manually specified device please?

Here is what I tried and the error that I got.
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
    </startup>
  <appSettings>
    <!-- IpAddressesDevices: 192.168.0.1,DeviceName1;192.168.0.2,DeviceName2 -->
	<add key="IpAddressesDevices" value="192.168.1.33" />
	<192.168.1.33>,<MediaSpeaker>;
    <!-- ShowLagControl: true or false -->
    <add key="ShowLagControl" value="false" />
  </appSettings>
</configuration>
```

XML Parsing error at line 13: Premature end of data in tag configuration line 2.

**Comment by SamDel** [comment]
This should work:

<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
    </startup>
  <appSettings>
    
	<add key="IpAddressesDevices" value="192.168.1.33,MediaSpeaker" />
    
    <add key="ShowLagControl" value="false" />
  </appSettings>
</configuration>

**Comment by skyiron** [comment]
Thank you. Configuration is now working!!
