### ISSUE TITLE
Not finding any Google Smart Speakers (After Firmware Update)

### ISSUE THREAD

**Issue by Geriatrix1** [SamDel/ChromeCast-Desktop-Audio-Streamer#88]
I've really enjoyed using this app, thanks. A few days ago I noticed it wasn't finding all my devices. I have a mixture of Chromecasts (both audio and video), a Lenovo clock, and 4 Google Home speakers. I've now realised that it isn't finding the Google Home speakers anymore. Well it seems to find one random one, and then flag a connect error to whichever one that it has found. I'm wondering if this is an issue with Google speakers. I've tried disconnecting and reconnecting them, and they work perfectly well in all other respects. Thanks.

**Comment by SamDel** [comment]
I think it's releated to the network. Have you tried to reboot the router and the devices?

**Comment by Geriatrix1** [comment]
Thanks. Yes, I've tried that. I noticed that all the devices appear on the cast tab of my Chrome browser, and I'm able to cast the audio from YouTube to them without any problem. I've also uninstalled the app and reinstalled without luck, and reverted back to 2.7. It's just odd - they're deffo connected to the same network too. Anyway thanks for the reply, I'll keep on fiddling with it!

**Comment by SamDel** [comment]
You can try to enable the logging. Maybe there are errors there!

**Comment by Geriatrix1** [comment]
OK thanks. BTW I can also play to all the undiscovered devices from my Desktop Spotify . In fact I thought that might be causing the problem so I uninstalled Spotify, but that didn't solve the problem. I've attached a log. I'm sorry, but I'm not savvy enough to understand it! If you don't have time to go through it don't worry! Cheers.
[log.txt](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/5284118/log.txt)

**Comment by SamDel** [comment]
An IP address is missing for some devices, see below. I'm not sure where it goes wrong. Maybe the settings file is corrupted, can you try a 'Reset Settings' on the options tab?


Discovered device: Shower Room Speaker :8009 null 

out [17:08:42][:8009] [NotConnected]: {"type":"CONNECT"}

ex []: Connect Value cannot be null.
Parameter name: host

**Comment by Geriatrix1** [comment]
Yes, I see what you mean. I've reset settings several times. No change. The bizarre thing is that the Bedroom Clock is basically a Google Mini with a clock but that connects perfectly. The Google Minis that don't connect are Kitchen, Shower Room, Bedroom 2 and Bathroom. From my router settings I can see the IP addresses for each of these. As I said I've uninstalled the app a couple of times with reboots before reinstalling it. And it used to work perfectly and was rock solid. Anyway, never mind, I can live without music in the shower! Thanks for your help, I just wondered whether Google had changed something at their end, But I guess you'd have heard if other users had the same problem. Thanks again, all the best.

**Comment by FA-Bubba** [comment]
FYI, I am experiencing something similar (Thread #87), and have tried several different solutions...  Most recently, I added the key for IpAddressesDevices: in the CONFIG file.  Results have varied, at times not finding one or more "GROUPS", possibly because the 'elected leader' wasn't found...

The current status of my DAS setup is 3 Google Minis are not found, even though they have static IP Addresses and are in the CONFIG file, and one Google Mini that is displaying as 'Orange' in the Device List.  ALL of these Minis are now replying to pings, 3 do not display in the Device List; and one displays, but has turned Orange.
___

I just did a "Reset Settings", and the previously 'Orange' Mini is no longer found, 1 Mini was found, and the other two were not found.  Also, one Speaker Group (All Speakers) is not populating; the other two Speaker Groups seem to be working as expected, casting to the speakers in each respective group...

I also, rebooted the Minis, but that did not enable them to show in the Device Window -- they all respond to "Hey Google...." inquires.

ALL of this started in the past 48 hours, and I am not aware of any system changes that may have caused this.

Running Version 3.0.0.0

Here's the latest Log:

[Log-2020-09-25-v3-0-0-0-MinisNotFound.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/5285427/Log-2020-09-25-v3-0-0-0-MinisNotFound.zip)

**Comment by SamDel** [comment]
The same issue as @Geriatrix1 , interesting. It looks like the minis changed the way they add the IP address to the discovery packages.

In [Setup 3.0.1.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/5286786/Setup.3.0.1.zip) a dump of the discovery packages is logged. Can you try and post the logs? (I don't have a mini myself.)

**Comment by FA-Bubba** [comment]
All of my Minis have had firmware updates since the last time I checked, but I don't know if I can figure out WHEN it happened...

Something interesting:  Even though the Minis are not displaying in the Device Window, the only one that is in a Speaker Group is in fact playing the Cast; oddly, that Mini is displayed in the Device Window, but in the 'Orange' color.  I have 3 other Minis that are not in any Group -- they used to populate into the Device Window, but haven't since this issue started (a few days ago).

All 4 Minis still reply to Pings, so they are on the Network, even if DAS can't find them...

I will try 3.0.1 later today.

**Comment by Geriatrix1** [comment]
I've installed 3.0.1 and taken a log. Thanks again for help.
[Log 3 - 3.0.1.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/5286926/Log.3.-.3.0.1.zip)

**Comment by FA-Bubba** [comment]
PS:  I added a Mini that was not in any Group to one of my Speaker Groups, and it started Casting!  Still not displaying in the Device Window, though.

I tried "Scan again...", but nothing changed (the Mini that was Orange remained as Orange).

Then I clicked "Reset Settings", and the Orange Mini disappeared, and another Mini populated in, but it was NOT the one I added to a Group -- it was a Mini that is not in any Group (and not Casting).  HOWEVER, the note at the bottom of its Device Box says: "Connected Casting: Desktop Audio Streamer".  BUT, It shows the 'Speaker Group Icon" in the bottom right corner, and when I adjust its volume slider, one of the Group's Volume Slider also moves!... More details on the attached screen shot.


[Log-2020-09-25-v3-0-0-0-MinisNotFound-2.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/5287009/Log-2020-09-25-v3-0-0-0-MinisNotFound-2.zip)

**Comment by SamDel** [comment]
@Geriatrix1 The log file you added is empty!

**Comment by Geriatrix1** [comment]
OK, just checking. :-) Sorry! 
[Log 3 - 3.0.1.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/5287167/Log.3.-.3.0.1.zip)

**Comment by SamDel** [comment]
Thanks, @Geriatrix1 can you post the result of [this url](http://192.168.1.84:8008/setup/eureka_info?params=version,audio,name,build_info,detail,device_info,net,wifi,setup,settings,opt_in,opencast,multizone,proxy,night_mode_params,user_eq,room_equalizer&options=detail) in your network.

It returns some data of the shower room speaker. I'm interested in how the version and IP address are in the results. 
You can blank out information about the ssid etc. of course!

**Comment by Geriatrix1** [comment]
Ok - here it is.
[shower result.txt](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/5287904/shower.result.txt)

**Comment by SamDel** [comment]
Thanks, the device has been updated to Version 12. 
In [Setup 3.0.2.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/5287921/Setup.3.0.2.zip) I added support for this version. Can you try?

**Comment by Geriatrix1** [comment]
Yea, success!! Although for some reason it’s not finding the bathroom mini, but that may be a local problem here. It’s found bedroom 2, shower room, and kitchen, and I’ve cast audio to the kitchen and it’s coming through loud and clear. Thanks so much. I'll play around with the missing mini later, but just on my way out. Thanks again!

**Comment by Geriatrix1** [comment]
Bathroom speaker now found, so all back to normal. Really appreciate the work you've done on this app, which I use daily. Cheers.

**Comment by SamDel** [comment]
Nice, thanks for helping! I'll make a 3.1 release of it later.

How's 3.0.2 for you @FA-Bubba ?

**Comment by SamDel** [comment]
[Release 3.1](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/releases/tag/v3.1)

**Comment by FA-Bubba** [comment]
I installed v3.1.0 Last night, and at first not all Speakers or Groups were found.  I checked the CONFIG file, and my static IP Assignments that I entered under v 3.0 were still there.  So I did a Reset Settings, and everything was found.  I selected two Speaker Groups, and all of those Speakers played the stream...

Sometime overnight, some speakers quit Casting, but were still in the Device Window.  I did Reset Settings again, and selected the same two Speaker Groups, and all Speakers in those Groups are playing.  It is now 3 hours later, and all are still playing.  I will continue to monitor...

Here's the Log:

[Log-2020-09-28-v3-0-1-0.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/5293055/Log-2020-09-28-v3-0-1-0.zip)

**Comment by SamDel** [comment]
I see some hick-ups in the night, but it looks good!

**Comment by FA-Bubba** [comment]
Was there any indication of what may have caused the hick-ups?

**Comment by SamDel** [comment]
No, it's around 2:09 AM, 2:18 AM, 2:45 AM, 3:32 AM, 4:24 AM and 4:40 AM.

**Comment by FA-Bubba** [comment]
Casting to the 1st Floor & 2nd Floor Speaker Groups seemed to be OK for about a day (after the "hick-cups" you noted on 
Sunday night, in your previous message)...  and yes, there were likely backups running then.

Tuesday morning, around 11:00 AM, both Speaker Groups dropped out, and turned the orange/tan color.  I did "Reset Settings",
and noticed several Devices had the note "Connected Casting: Desktop Audio Streamer", even though I had not yet selected
any devices or Groups (see ScreenShot).  So I did another Reset Settings, with the same result.

HOWEVER, while I was typing this, those comments disappeared, so I selected the two Speaker Groups, and DAS is now 
playing to all.

Any indications of why the two groups dropped-out in the first place?


[DeviceWindow-2020-09-29.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/5300201/DeviceWindow-2020-09-29.zip)

**Comment by SamDel** [comment]
The problems start at 11:06:04 AM, and it takes about 15 minutes till the errors disappear.
There is still communication with the devices, but about 50% fails. As if the network is only functioning for 50%. Maybe too much network load, but it's hard to tell.

**Comment by rdbisme** [comment]
Just a comment: I had a tailnet rerouting `192.168.1.x` addresses, which are also the address of my local PC. So basically check your IP config is sane. 

I have changed the IP pool of my local network to be different from the one managed by the VPN and everything worked as expected :)
