### ISSUE TITLE
Synchronising 2 Chromecast Audio

### ISSUE THREAD

**Issue by s4n3** [SamDel/ChromeCast-Desktop-Audio-Streamer#9]
I have 2 chromecasts audio (one actually included in JBL Playlist speaker) and they are out of sync (when playing simultaneously).
Am I doing something wrong ?

**Comment by SamDel** [comment]
There's no automatic synchronization between two devices in the application.

With this little trick you can sync the devices:
- Enable the lag control in the config file which is in the install folder. Set "ShowLagControl" to true.
- (re)Start the application and start the devices.
- Put the lag control slider on 'minimum lag' for a couple of seconds, that will clear the buffers on all devices.
- Then you can put the slider on 'best quality' again, the devices are in sync.

Maybe that process can be automated in a future release.

**Comment by resom78** [comment]
Hi,

About the lag control, I saw in your code that in fact it skips some audio packets!! It's not really a latency control since it degrades the audio quality!
Why did you manage the latency in this way?

**Comment by SamDel** [comment]
You're right. When you use the lag control and it's not on the maximum value it removes every x-th packet from the audio stream, reducing the quality. You should only use it when latency is more important than quality.

I was experimenting with it. The only way I could think of to reduce the latency was keeping the buffer on the Chromecast device low.

**Comment by SamDel** [comment]
Version [2.0](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/releases/tag/v2.0) supports groups. 

You can create groups in the Google Home app and use them in this application to play devices synchronized.

Please let me know if it works for you!
