### ISSUE TITLE
Save Settings

### ISSUE THREAD

**Issue by StevoGenix** [SamDel/ChromeCast-Desktop-Audio-Streamer#91]
Hi
When I adjust the options, on the GUI there is only a reset settings option, However when I make my settings and then use the program at a later date, the settings have not been saved.
Particularly it is the mute desktop audio feature, I select it however it always is deselected when I go back into the settings menu and hasn't muted the desktop audio - this is after a restart
Am I following the correct procedure for making settings?

**Comment by SamDel** [comment]
The setting are saved in `C:\Users\<username>\AppData\Local\ChromeCast\<random>\3.1.7.0\user.config`
Does that file exist?

**Comment by StevoGenix** [comment]
Yes it does, however the subfolder that you have listed as "3.1.7.0" on my PC is "3.1.0.0" I redownloaded the latest version, however I have not had chance to test it out to see if reinstalling will work. But I will report back as soon as I can

**Comment by SamDel** [comment]
Sorry, "3.1.0.0" is the right version. "3.1.7.0" is a development version on my PC to try things out.

**Comment by StevoGenix** [comment]
Yes, that file is in the folder and not "read only" I have just done a test, by selecting Automute desktop,, show window on startup,  I close the application (cross in the right hand corner)  and it is then minimised to my intray. I then reboot the PC and it is back to them options deselected.
It's not to much of an issue as otherwise the application works great. If there is nothing that can be done it does not matter to much I am still able to enjoy the application.
Best Regards

**Comment by SamDel** [comment]
Maybe the function that saves the settings is not triggered when you reboot the PC. The settings are also not saved when you minimise to the systray. 

Can you try right-clicking the tray icon, and then 'Close'. Then they should be saved.

**Comment by SamDel** [comment]
There's a bug [here](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/blob/d878c1a426bb09c8197e6167942d6d7bbe4e28a0/Source/ChromeCast.Desktop.AudioStreamer/MainForm.cs#L179). When you have the option 'Minimize to systray when closing' checked, saving the settings is never triggered.

Can you try [Setup 3.1.9.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/5736112/Setup.3.1.9.zip)?

**Comment by StevoGenix** [comment]
Hi Happy New Year
That is the option I have selected so perhaps that is it .. I will try the other version and get back to you.

**Comment by StevoGenix** [comment]
Thank you 
I have downloaded that version, I have selected the options that I want and after a few restarts it seems to save them options. So it appears for now to work.
Thank you
