### ISSUE TITLE
Devices drop-out when Internet is not available

### ISSUE THREAD

**Issue by FA-Bubba** [SamDel/ChromeCast-Desktop-Audio-Streamer#92]
I recall this issue of Internet Access needed by DAS was addressed this past Fall, but I could not find that thread...

My home recently had a loss of Internet for about 48 hours; during that time, electrical power was OK, and my home network was working.

The outage occurred around 4:00 AM, so I did not discover it until later that morning.

The Devices in the DAS display were mostly orange, and not connected (I believe you confirmed this result was due to loss of Internet access in the earlier thread).  Once the cable provider corrected the Internet outage, restoring DAS performance was quite troublesome.

Here's what I tried, and what happened:
1. I confirmed good internet connection from my PCs and my phone. -- All OK
2. I tried "Reset Settings" in DAS, but most of the devices remained off line.
3. I tried "Scan again for devices", but no change.
4. I closed DAS, and then reloaded it, but most Devices were still off line.
5. I tried "Reset Settings" again, but most were still the Orange color.
6. I then walked around and powered each Device Off, then back On, then closed and reloaded DAS -- this brought most, but not all Devices back on, and DAS was able to Stream again to the available Devices.
7. I rebooted the PC that runs DAS, and then ALL Devices populated into the Device box, and I was able to stream to all Devices.

I don't recall why DAS has a requirement for Internet access -- can that be changed?

Walking around and rebooting every Device is tedious, and since all of my Devices have static IP addresses, I'm not sure why this was necessary -- Any ideas on this?

If this happens in the future, I may just shut-down the power for the whole house at the Master, to reboot all Devices at once, unless you can suggest a better approach.

Thanks!

**Comment by SamDel** [comment]
Do you mean [this thread](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/issues/87#issuecomment-670975963)?

> Test results:
> 
> - When a device is playing and you unplug the (main) internet cable, DAS continues playing.
> - When a device is idle and you unplug the (main) internet cable, DAS can start streaming to the device.
> - When a device is turned on when no internet is available it refuses connections ("Connect Error") until internet is available.

**Comment by FA-Bubba** [comment]
Yes, that was the thread that previously discussed DAS needing an internet connection...

In that thread, I noted that someone *might* want DAS on their local home network, but don't want an internet connection...

Do you think it is possible to enable DAS to work without the Internet?

Thanks!

**Comment by SamDel** [comment]
I did the same test again. But now not streaming (with DAS) to a 'real' Chromecast device but streaming to a Raspberry Pi with [this](https://github.com/SamDel/ChromeCast-Device) software. Both DAS & the software of the new project don't need internet (as far as I know).

In this scenario:
> - When a device is turned on when no internet is available it refuses connections ("Connect Error") until internet is available.

DAS can connect to the Raspberry Pi device and start streaming. So it must be the 'real' Chromecast software that needs an internet connection when it boots. DAS & [this project](https://github.com/SamDel/ChromeCast-Device) don't need an internet connection.

**Comment by FA-Bubba** [comment]
Thank you for the follow-up...

I haven't yet looked at the other software you referenced...  Is it something you would recommend using instead of DAS ??  (considering I am now casting to 10 Speaker Pairs, each pair driven by ChromeCast Audio, to 3 Google Minis, and to one Google Hub -- I like the multi-room music it delivers, and with using Groups, the music is always in-sync).   Also, I may add more minis/Speaker Pairs as needed...

I am not currently using any Linux devices, but have a couple of old PCs that I could install Ubuntu on, but my streaming source is iTunes on a PC (I suspect I could identify another App to manage the MP3 files, and PlayLists, but it strikes me a a LOT of work just to circumvent an issue that (so far) has only occurred rarely.

Since ALL of my speakers are driven by a ChromeCast device (CCA, Mini, Hub, etc), I am guessing my audio architecture would not work in the new environment you described above.   ...and given my current level of satisfaction when things are working as expected, I guess my best approach is to stay with the current model, and suffer through any Internet outages, which have been few & far in between.

In the long run, I am still open to suggestions as they may apply to my current configuration.

Thank you!

**Comment by SamDel** [comment]
The other software is not to replace DAS, but to create a device to stream audio to (next to the Chromecast devices).

I used it to test which device needs an internet connection, DAS or Chromecast. In my test I had a setup without Chromecast devices, only a Raspberry Pi device attached to speakers and a Windows device with DAS installed. That setup worked fine without an internet connection. So it appears to me that it's the Chromecast devices that need an internet connection, not  DAS.

**Comment by FA-Bubba** [comment]
OK, I understand, Thank you...

I guess the Chromecast Devices need the internet connection so they can update their Firmware.  (Which only updates after the Device is rebooted).

I'll click "Close with Comment" below.
