### ISSUE TITLE
Update to V3.2, application stopped working

### ISSUE THREAD

**Issue by generic-user** [SamDel/ChromeCast-Desktop-Audio-Streamer#94]
Hi, I installed the new 3.2 version. But after completing setup. Launching application failed without any error message.

![image](https://user-images.githubusercontent.com/1516035/105627789-362d0900-5e39-11eb-85a8-a755d9c5b880.png)
![image](https://user-images.githubusercontent.com/1516035/105627804-4c3ac980-5e39-11eb-83e4-b43287ff210c.png)

**Comment by SamDel** [comment]
Is there an error in the Application log in the Event Viewer in Windows?

**Comment by generic-user** [comment]
There is something about the restart manager not being able to ... error 10010

![image](https://user-images.githubusercontent.com/1516035/105628184-b3f21400-5e3b-11eb-9646-6d7db737c8e9.png)

**Comment by generic-user** [comment]
OK, so 

- I went back to version 3.1 witch worked OK
- Reboot
- and then reinstalled 3.2
- now it is launching as expected

Thanks 🥇  for the ultra-fast response. I'll close this issue now. Probably a temporally system glitch ...

**Comment by SamDel** [comment]
Nice, thanks for letting me know!

There's some information about the restart manager here:
[https://docs.microsoft.com/en-gb/windows/win32/rstmgr/about-restart-manager?redirectedfrom=MSDN](https://docs.microsoft.com/en-gb/windows/win32/rstmgr/about-restart-manager?redirectedfrom=MSDN)

> The primary reason software installation and updates require a system restart is that some of the files that are being updated are currently being used by a running application or service.

It can be some (system) files were locked.
