### ISSUE TITLE
Fixed IP Addresses for Audio Devices

### ISSUE THREAD

**Issue by FA-Bubba** [SamDel/ChromeCast-Desktop-Audio-Streamer#97]
I'm not sure where this topic belongs... Please re-classify as necessary.

You may recall I started using fixed IP Addresses for all of my Google speakers (Chromecast, Home Hub & Home Minis) as a way to stabilize their discovery by DAS.  I did that in Feb 2020, and you provided this format for the key:
<add   key="IpAddressesDevices" value="192.168.1.13,Family Room Speakers;192.168.1.25,PlayRoom Speakers;192.168.1.11,Office Speakers;192.168.1.17,.............." />

Doing that greatly stabilized the casting audio performance.   This week, I was adding a new Google Mini, and I learned that Comcast has eliminated the ability to assign Fixed IP Addresses**, so I was wondering if DAS has a way to use MAC Addresses instead of IP -- since MAC Addresses don't change it would provide another way to uniquely identify a speaker...

Alternatively, I am thinking of ditching Xfinity's Gateway, and using my own Router, but I first need to research if that will cause any degradation of my TV and Voice services.

**Odd that Comcast has prevented me from assigning new fixed IPs, but it has retained those that I previously assigned!!!

**Comment by SamDel** [comment]
The MAC address [is used](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/blob/f86d36e583b4dd7568f6b9ceeedf3453c9a4d750/Source/ChromeCast.Desktop.AudioStreamer/Application/Devices.cs#L149)  by DAS to check if a newly discovered device is already in the device list. 

You can't use the MAC address instead of IP, the IP is always used to connect to a device.

**Comment by FA-Bubba** [comment]
OK....  I now have to decide whether to include DHCP devices in the "key" or not...

FYI, this is the key I am referring to:
add   key="IpAddressesDevices" value="192.168.1.13,Family Room Speakers;192.168.1.25,PlayRoom Speakers;192.168.1.11,Office Speakers;192.168.1.17,.............. etc." 

If I do not add new devices to the above key, I am assuming they will be found through the normal means, correct?
What happens if I add a device to the key, and it's IP address later changes?  Will that cause problems?

Thanks!

**Comment by SamDel** [comment]
That's correct, they will be found through the normal means.

An IP change should be detected, the MAC address is used for that.
